Yelp/Tron

tron/core/serviceinstance.py
Current service monitor task run into a loop when node permanently down.
In this case notify code will try to cancel the monitor task, but the queue happens after the observer being notified.
=> Service monitor task should be requeued before notify

.gitignore, Makefile, Vagrantfile, docs/developing.rst, vagrant/hosts, vagrant/tron.default
This adds a multi-node Vagrant environment consisting of a tron 'master' node
and three 'batch-*' nodes for jobs/services.
The master node is fully configured, and ready for addition of the nodes and node_pool
entries via tronfig, which is documented in docs/developing.rst.
The tron master node is currenly Ubuntu 10.04 LTS, due to limitations in the debian package
build process. This also mirrors the most common deployment pattern for tron at the time of
writing, hopefully with a view to making this easier to migrate from.
=> Vagrant 'development playground' environment

Vagrantfile, tests/commands/display_test.py, tests/config/config_parse_test.py, tron/api/adapter.py, tron/commands/display.py, tron/config/config_parse.py, tron/config/schema.py, tron/core/job.py, vagrant/pretend_tron_service.sh, vagrant/sshd_config, vagrant/tronfig/MASTER.yaml, vagrant/tronfig/deploy-tronfig.sh, vagrant/tronfig/other_namespace.yaml, vagrant/tronfig/test_namespace.yaml
When supporting Tron with a large configuration managed by many people and teams, it gets very difficult to see who owns what. 'git blame' and looking at the code of individual jobs, basically.
Namespaces help with this, and naturally comments in the YAML files help too. However, this is pretty basic and very difficult to enforce.
This PR adds the following fields to the configuration, and extends visibility to the API and Tronview.
* owner (string)
* summary (string)
* notes (string)
These should allow job/service authors to give reasonable hints as to who to contact in the event of maintenance/update, what the job/service does, and arbitrary notes (such as links to runbooks, details of business impacts, etc).
The fields are all optional, and default to the empty string.
The PR also …
=> Add job and service support fields: owner, summary, notes.

tests/commands/display_test.py
When running make tests the build fails with the following message:
========================================================================
FAILURES
The following tests are expected to pass.
========================================================================
tests.commands.display_test DisplayJobsTestCase.test_format
------------------------------------------------------------
File "./tests/commands/display_test.py", line 132, in test_format
lines = self.do_format()
File "./tests/commands/display_test.py", line 127, in do_format
out = DisplayJobs().format(self.data)
File "./tron/commands/display.py", line 176, in format
self.out.append(self.format_row(row))
File "./tron/commands/display.py", line 115, in format_row
for i, value in …
=> Fixing build failure

tron/core/jobrun.py
The cleanup method uses a different name during cleanup. So all jobrun events are not properly cleaned up.
=> fix event memory leak

tron/ssh.py
In twisted connection.py, deferreds[channel.id] is set to [] after channel close. Latest twisted use del self.deferreds[channel.id][:], but both will leak 1 int and 1 empty list per command execution. Memory will be release after connection close but in a real world usage ssh connection usually persist the entire duration of tron uptime.
All the code use self.deferreds expect non existent value, so it is safe to not leave an empty list behind.
=> extra cleanup after twisted ssh channel close

docs/command_context.rst, tests/utils/timeutils_test.py, tron/utils/timeutils.py
Primary: @yyejun 
This adds an "hour" variable to the command context to make it easier for people to have hourly batches who don't want the granularity of seconds with unixtime.
=> Add 'hour' to the command context

tron/ssh.py
Attempt reduce tron memory usage. Only the last ssh network data will be saved to disk.
=> only keep last buffer from ssh connection

.gitignore, Makefile, debian/control, debian/init.d, debian/rules, debian/tron.links, setup.py, tests/commands/client_test.py, yelp_package/trusty/Dockerfile
Note: this also makes the python version in the virtualenv 2.7. Happy to do that in a separate PR if we want to?
I'm copy+pasting a lot of this from paasta, and am certainly no expert at debian packaging, so I'm open to feedback.
still to do: 
EDIT: seems the init script is broken anyway. My change hasn't broken it any more?
=> [wip] use dh-virtualenv to package tron

tests/config/config_parse_test.py, tron/config/config_parse.py
use the more reliable getpass.getuser() instead of expecting a USER env
var to be present.
Fixes #315
=> dont assume the USER env var

tron/ssh.py
this means we allow unicode characters. should be ok?
=> encode command as utf-8

bin/tronfig, tests/api/controller_test.py, tests/api/resource_test.py, tests/config/manager_test.py, tron/api/controller.py, tron/api/resource.py, tron/commands/client.py, tron/config/manager.py
If a POST request with an empty string is sent, the namespace config file will be deleted.
=> Add option to delete namespaces in tronfig

bin/tronctl, docs/man_tronctl.rst, tron/api/controller.py
I would like to change the name of this command to "rerun" like in paasta. I think it makes more sense for jobs.
Once we remove the service functionality entirely I'll deprecate the "restart" command entirely in favor of rerun.
=> Added rerun for re-running jobs instead of restart

bin/tronfig, tron/config/config_parse.py, tron/config/manager.py
- add `-V` option to validate a single namespace file
- add `-D` option to do a full validation of a config directory
- comment out some validations for options that we intend to move out of master namespace into separate config file
- drop code related to editing namespaces directly
=> Local validation options, cleanup of unused functionality

example-cluster/README.md, example-cluster/start.sh, tox.ini, tron/api/resource.py
Adding a tox env for the example cluster to make it easier to start. I was getting errors on my devbox with the old commands because I had an old version of docker-compose.
Also, there was one unicode error left, since it doesn't use the `respond` helper. Just adding `b'` here for completeness. After this change, `curl localhost:8089` works.
=> Improve example cluster startup, and fix one remaining unicode error

tron/core/job.py
test it through running example-cluster, changing monitoring configuration, and curl the job via api.
=> reconfigure jobs if monitoring setting has been updated

.travis.yml
Currently we are not generating new versions of the docs on pythonhosted because we are not uploading to pypi on new releases. This should allow this to happen automatically.
=> Upload to pypi on tags

tests/core/actionrun_test.py, tox.ini, tron/core/actionrun.py
To fix the issue where Tron can't restore the state for some old job runs because the action dependencies have changed. Described in more detail in https://jira.yelpcorp.com/browse/TRON-210.
action_runs_for_actions is only used in _is_run_blocked, to check the state of required actions. If a "required" action isn't in the action map, that action didn't exist when that job ran, so it's not really required and we can ignore it.
The real problem is that Tron assumes the current action graph applies to all job runs, but that seems much harder to fix.
Plus one tiny change to the example cluster so it will clean up after you exit - realized I've just been leaving these containers around.
=> Ignore unknown ActionRuns

bin/action_runner.py, tests/actioncommand_test.py, tests/bin/action_runner_test.py, tron/actioncommand.py, tron/core/actionrun.py
- changes action_runner to use argparse
- add the run_id as an arg to go in the status file
- just use pyyaml rather than the tron version, so that you don't need the tron package installed to use it. I'm open to reverting this, it mostly makes it easier to test (and the performance impact will be nbd for the action_runner)
here's the lines from the state file that the action_runner left behind
```
root@26a95ee742b5:/tmp/tron/MASTER.test.9085.first# cat status
{command: echo hi >> out && sleep 20, pid: 8540, return_code: null, run_id: MASTER.test.9085.first}
{command: echo hi >> out && sleep 20, pid: 8540, return_code: 0, run_id: MASTER.test.9085.first}
```
=> store the actionrun id in the status output by action_runner

bin/check_tron_jobs.py, tests/bin/check_tron_jobs_test.py
If a job is scheduled to run now, but there are still jobs running, couple of scenarios might happen:
1. if allow_overlap is True, it runs anyway
2. if queueing is True, it's marked as queued
3. if queueing is False, it's marked as cancelled
Currently, we treat  (2) and (3) as job is stuck for some reason and send event to sensu. Let me know if you have other thought about the definition of stuck.
Make test works. And I also tested it through kwatest at devc and playground.
=> add stuck status for jobs

setup.py, tests/commands/display_test.py, tron/commands/display.py
The cast in format_value ensures that all values (including None, which caused TRON-217) are strings. It used to cast all values with `unicode()`, but that was taken out in the python3 conversion. Using str() now. I know this is bytes for python2, but the value gets converted to unicode elsewhere and tronview still works with this change, so meh?
Updated the tests for display to cover that case, and took out some data that wasn't being used.
=> Fix tronview bug and include six in install_requires

tests/config/config_parse_test.py, tron/api/adapter.py, tron/commands/display.py, tron/config/config_parse.py, tron/config/schema.py, tron/core/job.py
I've searched at tronfig and tronfig-notprod repos, only job "hello-world" at devc uses notes/summary/owner. If I got ship it for this, I would update that job as well as validate_tronfig.py at tronfig-notprod before this one being merged.
=> rmove notes/summary/owner

tests/commands/display_test.py, tron/commands/display.py
tronview is broken in tronplayground right now - this fixes
```
robj@tronplayground-uswest1adevc:~  % tronview
File "/usr/bin/tronview", line 150, in <module>
main()
File "/usr/bin/tronview", line 135, in main
output = view_all(options, client)
File "/usr/bin/tronview", line 70, in view_all
display.DisplayJobs().format(client.jobs()),
File "/opt/venvs/tron/local/lib/python2.7/site-packages/tron/commands/display.py", line 191, in format
self.out.append(self.format_row(row))
File "/opt/venvs/tron/local/lib/python2.7/site-packages/tron/commands/display.py", line 127, in format_row
for i, value in enumerate(self.sorted_fields(fields))
File "/opt/venvs/tron/local/lib/python2.7/site-packages/tron/commands/display.py", line 122, in sorted_fields
return …
```
=> remove owner from tronview display

bin/check_tron_jobs.py, tests/bin/check_tron_jobs_test.py
add one unit test for the scenario that user manually start a job and it's stuck.
make test pass
=> improving stuck job checking when runtime of job run unsorted

tests/scheduler_test.py, tron/scheduler.py
This fixes this stacktrace:
```
File "/opt/venvs/tron/local/lib/python2.7/site-packages/twisted/internet/base.py", line 805, in runUntilCurrent
call.func(*call.args, **call.kw)
File "/opt/venvs/tron/local/lib/python2.7/site-packages/tron/core/job.py", line 338, in run_job
self.schedule()
File "/opt/venvs/tron/local/lib/python2.7/site-packages/tron/core/job.py", line 293, in schedule
self.create_and_schedule_runs()
File "/opt/venvs/tron/local/lib/python2.7/site-packages/tron/core/job.py", line 260, in create_and_schedule_runs
for job_run in self.get_runs_to_schedule(ignore_last_run_time):
File "/opt/venvs/tron/local/lib/python2.7/site-packages/tron/core/job.py", line 387, in get_runs_to_schedule
next_run_time = self.job.scheduler.next_run_time(last_run_time)
File …
```
=> Only localize datetimes when they lack tzinfo

README.md, docs/man/tronfig.1, docs/man_tronfig.rst, tox.ini, tron/config/schema/tronfig_schema.json
I tried to update the documentation on pythonhosted.org, but it rejected me and said it was deprecated and told me to use readthedocs.
I activated it and enabled the webhook and would like to make this transition.
=> Move tron documentation to readthedocs.io

Makefile, dev/config/MASTER.yaml, dev/config/_manifest.yaml, dev/logging.conf, docs/developing.rst
I used this technique to make it easier to develop the frontend stuff.
It is lighter weight than the example cluster.
=> Added a 'make dev' target to iterate faster with local development

bin/tronctl, bin/tronview, setup.py, tron/commands/cmd_utils.py
This is a first iteration of tab complete. It parses the output of the /api/jobs endpoint of the default server.
We have {{args.server}} that will hold the tron server to use. It can optionally be specified with {{--server}}, or it will take the default of localhost. But, i cant use this variable, because at the time argcomplete is called, the {{args}} var has not been populated.
So instead, i added a helper function to give the default server as its hardcoded in tron/command/cmd_utils.py .
But is this default what we're using going forward? My understanding is eventually we want devs to be able to {{tronview}} from their devbox. Having the default as localhost wouldn't allow this.
=> First pass at tab complete

bin/generate_tron_tab_completion_cache, bin/tron_tabcomplete.sh, debian/tron.links, tron/commands/cmd_utils.py
If tab complete cache file does not exist, it will fallback to hitting api
Also adds the debian links file to automatically enable tab completion
I'm cargo-culting the _tabcomplete.sh file from what we have in paasta. I think this might enable zsh autocompletion too? But i haven't tested it.
This is paired with the internal review r:285778 , which has the puppet code that populates this cache file.
=> Allow tab complete to read from cached file

tron/utils/trontimespec.py
Fixes a crash when restoring a job with next run time non-existent in specified timezone.
=> Dont try to localize time with tzinfo

tron/serialize/runstate/shelvestore.py
Restoring from state file created by Python 2 fails in Python 3 due to reasons.
P2Shelf extends the base Shelf class, replicates DbfilenameShelf and passes around arguments required to make it work in py3.
manually tested:
- loading py2 state in py3 and verifying returned values using ShelveStateStore interface
- modifying state in py3, loading it in py2 and verifying the change
=> Implement and use backward compatible Py2Shelf

tests/config/config_parse_test.py, tests/config/config_utils_test.py, tron/config/config_parse.py, tron/config/config_utils.py, tron/config/schema.py
Master config: add clusters list
Jobs: add service, deploy_group
Actions: add executor, cluster, pool, cpus, mem, service, deploy_group
Validates that any action with executor: paasta either contains service and deploy_group, or its parent job does. Also validates that the cluster in actions is part of the list of clusters.
Next step will be using these values in the Job/ActionRun objects.
*Also includes a fix to the scheduler test that was failing.
=> Paasta executor configs

tron/utils/trontimespec.py
No obvious reason to have a loop and advance by 24 hours.
=> Only try advancing the time by one hour when localizing

bin/tronfig, itest.sh
fixes an issue where tronfig would fail without a namespace argument
=> use the resolved namespace in tronfig

.dockerignore, .gitignore, .travis.yml, Makefile, README.md, debian/control, dev/req_dev.txt, itest.sh, osx-bdb.sh, setup.py, tests/serialize/runstate/shelvestore_test.py, tox.ini, tron/serialize/runstate/shelvestore.py, yelp_package/trusty/Dockerfile, yelp_package/xenial/Dockerfile
Apparently i didn't test Py2Shelf enough.
Python 2 through some db-detection logic in `anydbm` defaults to using bsddb module that was deprecated and removed from Python 3. It is recommended to use `bsddb3` module instead.
Since all our states are BDB, let's just use that directly and eventually replace it with another storage mechanism.
This adds some linux dependencies and makes life on OSX harder. To run tests we now need to `brew install berkeley-db` and export some env vars before running tox. I've included `osx-bdb.sh` script with relevant exports and made a section about it in README.md.
Also added some folders to .dockerignore because uploading half a gigabyte to docker daemon is not fun.
=> Use bsddb3 directly

bin/generate_tron_tab_completion_cache
Luckily this can be done in "1" api call. But on prod it does take ~dozens of seconds and produces 11k lines of output.
=> Print out job runs and action runs in tab completion cache

tests/commands/cmd_utils_test.py, tron/commands/cmd_utils.py
The original implementation of this gave "all" the possible things you could be completing, which is thousands.
This is a tad "smarter" for what humans are probably expecting, which doesn't bother giving you fine-grained suggestions until you type in a complete job.
=> Make more sane tab completions for busy tron servers

tron/core/actionrun.py, tron/mcp.py
The traceback doesn't show up in our error log for syslog reasons (multi-line). This makes it so we only have one line per error (so it will show up!)
=> Do a better job at printing exceptions when there are command render problems

tests/core/job_test.py, tests/utils/timeutils_test.py, tron/core/job.py, tron/utils/timeutils.py
macro_timedelta was failing if start date includes tzinfo. This was causing errors in DateArithmetic.
Made everything in timeutils handle timezones, and added tests.
Also changed manual_start to include tzinfo in the run_time if the job has it.
=> Timezone date context bug

tests/core/action_test.py, tests/core/actionrun_test.py, tests/core/job_test.py, tests/core/jobrun_test.py, tron/core/action.py, tron/core/actionrun.py, tron/core/job.py, tron/core/jobrun.py
Passing all the new config values around. Major change is in actionrun: now ActionRun just handles the state machine, and the subclasses (SSH, PaaSTA) implement stuff related to commands.
PaaSTA action run just prints for now, check this output from the example cluster!
root@940d5614644a:/work# tronview MASTER.test.1597.second
Action Run          : MASTER.test.1597.second
State               : succeeded
Node                : tron@batch1
Command             : echo hi >> out
Bare command        : echo hi >> out
Start time          : 2018-03-23 22:37:59
End time            : 2018-03-23 22:37:59
Exit status         : 0
Requirements:
Stdout:
Would have run command for service foo from deploy group bla on cluster None in the None pool, with 5.0 cpus and None MB memory.
Stderr:`
=> Use PaaSTA config values in runs and create PaaSTA action run

bin/action_runner.py, bin/action_status.py, tests/bin/action_status_test.py
#action_runner produces lines of yaml, whilst this script assumed that the
status file is a single blob of yaml. fix action_status.py to
1) parse each line as yaml individually
2) take the last line as the source of truth for any fields to be
printed
```
(tron) robj@tronplayground-uswest1adevc:~  % python action_status.py /tmp/tron/MASTER.qui_test_timezones.234.sleep print
{'command': 'sleep 9m', 'pid': 3904, 'return_code': None, 'run_id': 'MASTER.qui_test_timezones.234.sleep'}
(tron) robj@tronplayground-uswest1adevc:~  % python action_status.py /tmp/tron/MASTER.qui_test_timezones.234.sleep pid
3904
(tron) robj@tronplayground-uswest1adevc:~  % python action_status.py /tmp/tron/MASTER.qui_test_timezones.234.sleep return_code
None
(tron) robj@tronplayground-uswest1adevc:~  % sudo …
```
=> fix the action_status command

tests/utils/timeutils_test.py, tron/utils/timeutils.py
utctimetuple converts tz-aware datetimes to UTC, and gmtime converts UTC time tuples to timestamps.
utctimetuple does no conversion for naive datetimes, and mktime assumes that the timetuple is local.
=> Fix timestamp with timezone and remove flaky test

tests/config/manager_test.py, tron/config/manager.py
Minor, but might as well avoid getting into an inconsistent state.
get_filename_from_manifest adds an entry to the manifest if the namespace is missing. We just want to exit instead.
=> Don't delete file if namespace is incorrect

example-cluster/config/MASTER.yaml, example-cluster/docker-compose.yml, example-cluster/images/batch/Dockerfile, example-cluster/start.sh, example-cluster/tronfig/MASTER.yaml
This is a slight departure from how the example-cluster worked before.
Due to the (current) way that tron is installed here, I can't use the action_runner on remote boxes. 
But I can with localhost, which is "probably" good enough.
Heck, do we even need "distributed" scheduling in the example cluster? Or can we drop that complexity too? Is it enough for tron to try to schedule to localhost? It still exercises the ssh stuff. Who really cares if the hostname is localhost or is "batch1"?
But I think this may become more important as we invest more into the action_runner and action_status
=> Added the action_runner for localhost on the example_cluster

tron/serialize/runstate/statemanager.py
Currently when state file is created, it can only be read by the same or more recent version of tron even if there were no changes to the schema. Let's assume current version is `0` and increment in future when backward-incompatible changes are made. This will allow current (and previous) releases of tron to read the state file.
=> Disconnect state version from release version

bin/tronfig, tron/config/manager.py
`tronfig -p` fails when namespace contains non-ascii characters.
=> Fix namespace with non-ascii crashing tronfig

example-cluster/start.sh, example-cluster/tronfig/MASTER.yaml, yelp_package/trusty/Dockerfile
A step closer to a kind of "prod smoketest" where we can see if a release can handle all the jobs on prod for real "for the next month".
=> Run the example_cluster under faketime 10x faster than real life

.gitignore, bin/tronrepl, dev/req_dev.txt, example-cluster/config/MASTER.yaml, example-cluster/start.sh, setup.py, tron/api/resource.py, tron/core/action.py, tron/core/actiongraph.py, tron/core/actionrun.py, tron/core/job.py, tron/core/jobrun.py, tron/serialize/runstate/shelvestore.py, tron/utils/__init__.py
The problem is that due to differences in bytes/unicode handling between py2 and py3, there are inconsistent key encodings in various collections in tron state.
This PR injects bunch of `maybe_decode`s in (hopefully) right places, so in theory after loading/storing the state everything will converge to unicode names/keys everywhere.
This will also be merged into py3 branch for consistency and will be cleaned up after we migrate.
Additionally:
-  i've copied `trond` with some changes into `tronrepl` to make it easy to inspect current state of tron, this is not recommended to use in production until I add readonly mode for state store class. to try it out, run it with the same arguments as trond, you will be dropped into ipython (pip install it beforehand) and you have some local variables …
=> Maybe decode all the things

bin/tronview, tests/api/resource_test.py, tests/commands/client_test.py, tron/api/adapter.py, tron/api/resource.py, tron/commands/client.py
tronview and tronweb work fine with this change. Unfortunately, I don't have the numbers to show how much it gonna speed up, but it shouldn't be worse at least. And this requires trond restarts.
=> speed up tronview command with zero args

.gitignore, bin/action_status.py, tests/bin/action_status_test.py
With the action runner we always run things with `shell=True`, which means we get a /bin/sh -c on everything.
The downside to this is that when you run `tronctl kill`, the signal doesn't "propagate" to the child process, so it gets reparented to 1.
This changes makes it so we signal the whole process group (like dumb-init).
Before this change, the proocess tree looked like this:
```
root@8ca2af892aaa:/work# ps -ef --forest
UID         PID   PPID  C STIME TTY          TIME CMD
root          1      0  0 00:04 ?        00:00:00 /bin/bash
root         16      1  0 00:05 ?        00:00:00 faketime -f +0.0y x10 trond -l logging.conf --nodaemon --working-dir=/nail/tron -v
root       1159     16  0 00:06 ?        00:00:00  \_ [ssh] <defunct>
root       1164     16  0 00:06 ?        00:00:01  \_ …
```
=> Always send signals to the full process group in the tron action runner

yelp_package/xenial/Dockerfile
Fix for
```
04:15:16 Step 8/8 : WORKDIR /work
04:15:16  ---> Using cache
04:15:16  ---> 5b6c272bd17f
04:15:16 Successfully built 5b6c272bd17f
04:15:16 docker run -t -v /ephemeral/jenkins/workspace/itest_xenial:/work:rw tron-builder-xenial python3.6 -m tox -vv --workdir .tox-docker -e py36
04:15:16 /usr/bin/python3.6: No module named tox
04:15:16 make: *** [test_in_docker_xenial] Error 1
```
Just copy-pasted `tox` installation commands for py3 from the trusty's `Dockerfile`.
=> Fix Xenial build

tox.ini
Before:
```
ERROR: Version in "./example-cluster/docker-compose.yml" is unsupported. Either specify a version of "2" (or "2.0") and place your s
ervice definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to
use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
ERROR: InvocationError: '/nail/sys/bin/docker-compose -f example-cluster/docker-compose.yml build playground'
```
=> Added docker-compose dependency to fix example-cluster on Trusty

bin/check_tron_jobs.py, tests/bin/check_tron_jobs_test.py
set check_every in monitoring script, so the developers can set alert_after in the config file.
=> set check_every in monitoring script

bin/action_runner.py, bin/action_status.py, docs/jobs.rst, tests/api/resource_test.py, tests/bin/action_status_test.py, tron/api/requestargs.py, tron/yaml.py
Commits:
* Fix namespace deletion bytes bug, by decoding the empty string that delete requests use. Manually tested this fix on playground, too.
* Slightly more docs on retries
* Explicitly separate YAML documents in action runner scripts. yaml.load_all can handle line breaks as long as the documents are separated by the document separator (---).
=> bug fixes: namespace deletion, reading long status files

example-cluster/README.md
```shell
$ docker ps | grep example-cluster_playground
f92fbde86f7a        example-cluster_playground                                                                                              "/bin/bash"              19 minutes ago      Up 19 minutes       0.0.0.0:8089->8089/tcp                             example-cluster_playground_run_1
```
Probably it's even better to provide a command which extracts the container id, i.e.:
```shell
$ EXAMPLE_CONTAINER_ID=$(docker ps -q -f status=running -f name=example-cluster_playground)
$ sudo docker exec -it $EXAMPLE_CONTAINER_ID /bin/bash
```
=> Fixed the example Docker container name in README.md

tron/core/job.py
Reverts Yelp/Tron#446 as it basically reverts Yelp/Tron#154
=> Revert "Fix reloading config ignores changes in `enabled`"

bin/action_runner.py, bin/recover_batch.py, bin/tronrepl, requirements.txt, tests/bin/action_runner_test.py, tests/core/actionrun_test.py, tests/core/job_test.py, tests/core/jobrun_test.py, tests/core/recovery_test.py, tests/mcp_test.py, tests/utils/collections_test.py, tron/core/actionrun.py, tron/core/job.py, tron/core/jobrun.py, tron/core/recovery.py, tron/logging.conf, tron/mcp.py, tron/utils/collections.py
TODO:
Edit: I'm going to let this feature set go out as a first pass and bump recovering unknown jobs *without* a restart for another PR - this'll catch 99% of our issues, and I'd like to get it out fast and iterate.
I'm going to build a deb and install on tronplayground to start experimenting.
=> Recover unknown batches

tests/actioncommand_test.py, tron/actioncommand.py
Fixes the AttributeError with state_data.
- type was class instead of NoActionRunnerFactory, causing an exception when trying to access status_path: https://github.com/Yelp/Tron/blob/master/tron/core/actionrun.py#L406
- python calls `__getattr__` if a property raises an exception. In actionrun, that raises an AttributeError
- The exception in getting `action_runs.state_data` raises an exception in the jobrun state_data property (https://github.com/Yelp/Tron/blob/master/tron/core/jobrun.py#L147), calling jobrun's `__getattr__`
- that calls action_run_proxy, which doesn't have state_data either, leading to the traceback we saw
=> Action runner factory should always be an instance

tests/core/recovery_test.py, tron/core/actionrun.py, tron/core/recovery.py
without this, the state machine remains in the unknown state until the
recovery job terminates.
=> set the machine state to 'running' before recovery

dev/logging.conf, example-cluster/logging.conf, requirements.txt, setup.py, tests/config/config_parse_test.py, tests/config/config_utils_test.py, tests/core/action_test.py, tests/core/actionrun_test.py, tests/core/job_test.py, tests/core/jobrun_test.py, tests/core/recovery_test.py, tests/mesos_test.py, tests/utils/dicts_test.py, tron/config/config_parse.py, tron/config/config_utils.py, tron/config/schema.py, tron/core/action.py, tron/core/actionrun.py, tron/core/job.py, tron/core/jobrun.py, tron/logging.conf, tron/mesos.py, tron/trondaemon.py, tron/utils/dicts.py, tron/utils/queue.py
Updates the API to be more general (no more paasta, just mesos and docker arguments) and uses taskproc to submit tasks to the mesos cluster.
Works for the action configurations I've tried so far. To do:
=> run tasks on Mesos

tests/core/actionrun_test.py, tests/mesos_test.py, tron/core/actionrun.py, tron/mesos.py, tron/trondaemon.py
Basically the same as using a global, but now it's namespaced under the class? So it's slightly nicer to change configuration and stuff like that.
Decided to do it this way instead of copying NodePoolRepository (https://github.com/Yelp/Tron/blob/62ebd9b8c45d4bce49c5943b1f319ee6c8f3aa85/tron/node.py#L60) since it doesn't actually work as a singleton... you can get different instances with NodePoolRepository() as many times as you want, it just enforces that get_instance() returns the same one. Didn't seem worth the extra code, but let me know if you like that better.
The enabling is proof-of-concept for how configuration would be done, need to follow up on using that configuration value properly in MesosCluster and adding the field to MASTER.
=> ClusterRepository for accessing Mesos clusters

tests/api/resource_test.py, tron/api/async_resource.py, tron/api/resource.py, tron/trondaemon.py
all GET request handlers use semaphore with capacity=10 to limit number of concurrent requests, POST requests acquire exclusive lock and drain capacity from semaphore before proceeding.
in this PR also:
- Remove reactor initialization
we've upgraded twisted a while ago, it already has the right logic to pick reactor implementation by default.
=> Bounded asynchronous API request handling

bin/action_runner.py
as it stands, if the caller of this script (normally ssh) is killed,
then the subprocess will exit with status code 141 (pipefail) when it
attempts to write any output to stderr or stdout of the child process to
sys.stdout.
this change instead tells the subprocess to send the child's stderr and
stdout to a pipe, and seperate threads iterate through those values and
print to the callers stderr and stdout. this'll mean that although the
action_runner will still have errors when it tries to write to stdout
and sterr, this won't affect the exit code of the subprocess, and as a
result the correct exit code is written to the status file
=> stream action_runner output from subprocess

tests/core/recovery_test.py, tron/core/recovery.py
each time an actionrun enters a terminal state (as it does with unknown)
an end time is set for the job.
this is particularly confusing when a job is set back into a running
state by the recovery job, since the job will be marked as 'running' but
also have an end time. this change resets the end time to None, such
that the job appears 'in progress' again.
=> reset actionrun endtime on recovery

bin/action_runner.py
if stdout or stderr disappear from under us and the thread reading them
crashes, then the stderr and stdout of the subprocess being run can
backup, and possibly prevent it exiting (see TRON-339 for an example of
docker doing this). catch any exceptions we get writing so that we
continue to read from the stderr and stdout of the subprocess.
example output in ``/tmp/{run_id}.log`` launching a pid that is interrupted:
```
WARNING:root:streaming 4 to <stdout>
WARNING:root:<stdout>: b'hi\n'
WARNING:root:streaming 6 to <stderr>
WARNING:root:foo-bar-123 running as pid 31721
WARNING:root:<stderr>: b'error\n'
WARNING:root:<stdout>: b'hi\n'
WARNING:root:<stderr>: b'error\n'
WARNING:root:<stdout>: b'hi\n'
WARNING:root:<stderr>: b'error\n'
WARNING:root:<stdout>: b'hi\n'
WARNING:root:<stderr>: …
```
=> handle failures streaming  to stdout/stderr

tests/api/controller_test.py, tests/core/actionrun_test.py, tests/mesos_test.py, tron/api/controller.py, tron/core/actionrun.py, tron/mesos.py
There's no difference between stopping a task or killing a task for task processing, so I use the same call except that "tronctl kill" would print the extra line saying "Warning: Mesos action might not be killed forcibly."
=> implement kill terminate for mesos actions

tests/config/config_parse_test.py, tests/mesos_test.py, tron/config/config_parse.py, tron/config/schema.py, tron/mesos.py
MESOS_MASTER_PORT, MESOS_SECRET, MESOS_ROLE would require changing the framework on reconfiguration, so leaving those for later.
=> Add default volumes and some other Mesos task settings to master config

bin/check_tron_jobs.py
Since an unknown action blocks a job just like a failed one, I think it's worth paging for. And with the recovery changes, UNKNOWN should be relatively rare and means something probably went wrong.
=> Unknown actions/jobs are critical alerts

bin/tronfig
tronfig needs one positional argument (source), so let's use that as the directory if -D is specified.
=> Fix validation of full tronfig directory

requirements-docs.txt
The docs have been broken since the 3.6 upgrade.
This splits out a unique docs requirements file so readthedocs.org can not try to build C-extension stuff.
=> Fix the docs

bin/check_tron_jobs.py, tests/bin/check_tron_jobs_test.py
The job runs are sorted by end_time, and then scheduled time. It covers two edge cases: (1) rerun job, which has the same scheduled time with the first job run. (2) manually job run between two scheduled job runs. The details of these edge cases are in TRON-359.
=> sort the job run based on endtime and scheduled time

bin/tronctl, tests/api/resource_test.py, tron/api/resource.py
If you get an uncaught exception from a request, the twisted default is to return a bunch of HTML. This makes it easier to tell what happened when you use tronctl.
The motivation for this was, if kill_task in Mesos fails, the user will get better feedback and can retry the kill command. But I think it will be nice in general.
=> Catch errors from commands and return a nicer error message

tests/config/config_parse_test.py, tron/config/config_parse.py, tron/config/config_utils.py
This catch type errors of rendering command, plus a special case like "$(variable) $(variable)s"
=> catch command rendering type error

cluster_itests/config/MASTER.yaml, cluster_itests/docker-compose.yml, cluster_itests/environment.py, cluster_itests/mesos.feature, cluster_itests/steps/itest_utils.py, cluster_itests/steps/mesos_steps.py, tox.ini
Also it prints the logs now on failure for debugging.
And now also has a tronctl helper for the future.
In the mid term, I don't want tron to have to "wait" for a task to be launched before connecting to mesos, I think that should happen at the same time the reactor starts, do reconciliation, etc. But we'll get there.
=> Make itests wait for tron to be connected to mesos

bin/tronctl, docs/man_tronctl.rst
Feedback from the CEP stuff, this apparently is something users are doing themselves a lot.
This is the very first pass of this feature, future version will actually run stuff, kick off dependent jobs, etc.
=> Added the prototype of the tronctl backfill command

.gitignore, example-cluster/start.sh, example-cluster/tronfig/MASTER.yaml, tests/eventbus_test.py, tron/eventbus.py, tron/mcp.py
same logic as in state manager. when sighup comes - we don't have time to wait for next loop iteration and handle shutdown there.
=> Eventbus sync shutdown

tests/config/config_parse_test.py, tests/core/actionrun_test.py, tron/config/config_parse.py, tron/config/config_utils.py, tron/core/actionrun.py
I would like to hear other thought before I proceed...
Instead of formatting string in old fashion way like:
```
%(PYTHON_ENV)s %(BATCHDIR)s/run.py
```
we can also format commands as:
```
{PYTHON_ENV} {BATCHDIR}/run.py
```
=> add string format support

bin/trond, bin/tronrepl, debian/tron.upstart, docs/man/trond.8, docs/man_trond.rst, example-cluster/start.sh, itest.sh, tests/trondaemon_test.py, tron/trondaemon.py
We're only using NoDaemonContext anyway, also:
- move debug handler to MCP class where signal loop lives
- keep manhole.sock path in MCP's attribute
- set pthread mask on every iteration in signal loop
- more logging
=> Deprecate --nodaemon option

tests/api/controller_test.py, tron/api/controller.py
- @solarkennedy previously removed enableall/disableall from tronctl when he added the backfill command, but there was some related code in the api controller that was left behind, which I have now also removed.
- Note that the JobCollectionController can no longer handle any commands.
- The controller's tests have been updated to check that any command received will raise an UnknownCommandError.
- pytest on the updated controller tests
=> Remove enableall and disableall from JobCollections in tron controller

debian/tron.upstart, tron/mesos.py
The `runner.stop()` call was the actual problem, I timed it and it takes up to 10 sec. The upstart default is 5 sec.
But I also took out the extra logging, which writes to the task's stderr file, since I don't think it's really necessary with reconciliation and it could increase the time as well.
=> Increase upstart timeout

tests/core/actionrun_test.py, tox.ini, tron/core/actionrun.py
If the task hasn't started or is already done, the "Can't find task id" message is kind of confusing.
=> Better feedback on killing Mesos actions if not running

tests/config/config_parse_test.py, tron/config/config_parse.py, tron/mesos.py
This was failing to connect if the address already had http in it, e.g. 'http://leader.yelp'. 
I wanted to make it more flexible, so that `http` was optional, and it could end in a `/` without breaking things.
The logic turned out to be more complicated than I thought, but the test cases should cover it.
=> Scheme optional for Mesos master address

tronweb/css/tronweb.less
These CSS things were not (apparently) associated with events
=> Fix colors on tronweb

tron/core/job.py, tron/core/jobrun.py, tron/mcp.py, tron/serialize/runstate/statemanager.py
When jobs are reconfigured and new runs are created, they don't trigger STATE_CHANGED handlers. If tron is restarted with such scheduled jobs, they will not be restored and older runs with stale config may be restored instead.
In this PR:
- eagerly save new scheduled runs
- f-stringify some log messages
=> Fix: restarting tron will restore outdated scheduled jobs

tests/core/actionrun_test.py, tron/core/actionrun.py
If someone uses `tronctl fail` on an action with retries, even if that action hasn't started yet, it will trigger restarts. So I've made fail move straight to the failed state, and replaced `fail` with `_exit_unsuccessful` everywhere we want to consider retries.
I also took back my change in https://github.com/Yelp/Tron/pull/522 so that you can still send kill requests to Mesos even if Tron thinks it's not running - for instance, if you manually failed it.
Internal ticket TRON-438.
=> Make fail final and move retries and exit logic out

docs/command_context.rst, tests/command_context_test.py, tron/command_context.py
According to [this document ](https://docs.python.org/2/library/string.html#format-string-syntax), there is no way to escape colon for format strings. Hence, I would like to use the pound sign instead. If the change gets merged, users would use "%(last_success#shortdate)s" rather than "%(last_success:shortdate)s". I will comment out the old_format action at yelpsoa-config later.
=> replace colon by pound for format string

tests/mesos_test.py, tron/mesos.py
- Bug (behavior): Retrying Mesos actions would produce duplicate log lines by the same number of retries attempted so far.
- Bug (code): Whenever a Mesos task was created and its logger initialized, it adds a handler to the logger to log output to stderr. Unfortunately, there was no check in place to prevent duplicate handlers from being added, so each task (retry) added another handler, producing another duplicate log output.
- Fix: Whenever we initialize a Mesos task, we check the number of handlers in the logger, and only add the stderr handler if there are no handlers present.
- Additional changes: Added a test for MesosTask's log initializer function to ensure only 1 handler is ever added to the logger.
- make dev
=> Add handlers check in MesosTask logger to prevent duplicate log lines

tests/utils/timeutils_test.py, tron/utils/timeutils.py
Tested manually to check that the behavior works as expected with and without timezones, but no unit tests because it's not our code anymore (yay!)
No timezone:
```
>>> import tron.utils.timeutils as timeutils
>>> timeutils.current_timestamp()
1537828767.0  # old value, an hour ahead
>>> timeutils.current_time().timestamp()
1537825185.666668  # new value
>>> 
(py36) qui@dev10-uswest1cdevc:~/work/Tron (010d171...) $ date +%s
1537825204  # a few seconds later, but new value is definitely correct
```
with timezone:
```
(py36) qui@dev10-uswest1cdevc:~/work/Tron (010d171...) $ python
Python 3.6.0 (default, Jan 13 2017, 00:00:00) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytz
>>> import tron.utils.timeutils as timeutils
>>> …
```
=> Remove to_timestamp method in favor of datetime.timestamp()

requirements.txt, setup.py, tests/core/action_test.py, tests/core/actiongraph_test.py, tests/core/actionrun_test.py, tron/core/action.py, tron/core/actiongraph.py, tron/core/actionrun.py
`dataclass` will be in stdlib in python 3.7 and there are clear benefits to using it as opposed to custom made objects with attributes so let's just gradually convert everything. I'm starting with Action here  because  that's the lowest level object and therefore smallest possible change.
=> Convert Action to dataclass

bin/tronctl, bin/tronview, tests/api/resource_test.py, tests/commands/client_test.py, tron/api/resource.py, tron/commands/client.py, tron/commands/cmd_utils.py
- Bug (behavior): If `tronview` and `tronctl` were given erroneous commands in some way, the programs show HTTP stacktraces (and other related errors), which ideally should not be shown to the user. 
- Bug (code):
1. `tronview`: Did not handle RequestErrors if raised when bad identifiers (for job runs or actions) were used.
2. `tronctl`: Despite the fact that we deprecated non-id commands, we still allowed tronctl to run without an id.
3. tron api: Although the tron client expects JSON error messages, the tron api returns HTML (with an error message embedded).
- Fix:
1. `tronview`: Ensure RequestErrors are handled, and an error message from tron api is displayed to the user.
2. `tronctl`: Enforce the need for at least job/jobrun/actionrun id as a positional argument
3. tron api:
- Create …
=> Remove http stacktraces from tronview and tronctl error messages

tests/core/actionrun_test.py, tron/core/actionrun.py
While switching actions to dataclasses (#544), @keymone changed where `constraints`, `docker_parameters` and `extra_volumes` were 'assembled' for a new action. While the code for the latter two attributes were copied correctly (using `e._as_dict()`), the code for `constraints` was not, resulting in a KeyError from taskproc when actions were scheduled to run on Mesos.
This PR is a small fix.
`make dev`: test running a job using `tronctl start`
=> Fix constraints passing incorrectly in actionrun

tron/trondaemon.py
When we restarted Tron at prod yesterday, Tron crashed after running for 2 mins. And the error message from the log at /upstart was shown as follows:
https://fluffy.yelpcorp.com/i/CDhTDjD58zp2WmVSg9F3hZ3HlfLT4mNx.html
Setting wantPID = 1 should fix this issue.
=> create pidfile for manhole socket

tron/mesos.py
None-type events are a normal case from taskproc that we should handle. For example, [offer timeouts](https://github.com/Yelp/task_processing/blob/2ebda4035e518b742d2e8e71267c510148526af5/task_processing/plugins/mesos/execution_framework.py#L149). This makes it easier to see the error message 'Failed due to offer timeout' from taskproc.
Otherwise the `Did not handle unknown type of event: {event}' logging can get verbose, since it includes the task config. 
also some f-strings
=> Handle non-Mesos events from taskproc

tronweb/coffee/actionrun.coffee
Display waiting for and publishing triggers data for actionruns in tronweb.
=> Triggers in tronweb

bin/tronctl, tests/api/controller_test.py, tests/core/job_collection_test.py, tron/api/controller.py, tron/api/resource.py, tron/core/job_collection.py, tron/core/job_scheduler.py
For example, if we want to move MASTER.test to test.test. the procedure would be:
1. review for the change at yelpsoa-configs
1. stop cron
2. tronctl move MASTER.test test.test
3. merge the change at yelpsoa-configs
4. start cron
Need to test: Is it OK to let tron_deployment_tool to deploy the new change? I think so, but need to test it.
=> add tronctl move command

tests/api/adapter_test.py, tron/api/adapter.py
Action's dependents is a set which JSON encoder refuses to encode, make it a list in repr adapter.
=> Convert action deps to list in repr adapter

docs/jobs.rst, tests/bin/check_tron_jobs_test.py, tron/bin/check_tron_jobs.py
For most jobs, alerting using their latest run is sufficient. Our current Sensu monitoring follows this model, such that if a run fails on one day and succeeds on the next, job owners will get an alert event followed by a resolved event. 
There are some jobs for which every run is precious; that is, if a run fails on one day but succeeds on the next, it does not mean the former run was fixed. Our monitoring currently DOES NOT cater to these jobs.
This PR modifies tron job monitoring via the check_tron_job script, such that if a job opts into it, owners can be alerted according to whether or not a there was a successful run on each given day, as opposed to a job's overall latest run was successful.
If a job does not opt in, job owners will still receive alerts the original way.
Key …
=> Add option for alerting every job in check_tron_jobs

setup.py, tests/api/resource_test.py, tests/mesos_test.py, tests/metrics_test.py, tron/api/async_resource.py, tron/api/resource.py, tron/config/schedule_parse.py, tron/core/jobrun.py, tron/mesos.py, tron/metrics.py
Need to add some tests, but otherwise ready for some comments.
Includes:
* timers for successful requests
* meters for all HTTP status codes
* meters for action run state changes
* counters for how many resources are being requested from Mesos
Example response: https://fluffy.yelpcorp.com/i/0VMHJDKh42PpNbkN3sFTbVJ8hZVffCx4.html
I would have to make some changes to taskproc for it to be able to use these gauges/timers instead of yelp_meteorite. Review soon! Either way, I think it's worth having these Tron metrics available. Planning to add a collector to put them into our system later.
=> Initial metrics endpoint

tests/trondaemon_test.py, tron/trondaemon.py
- Problems:
- In the event a pymesos process encounters an error, it will attempt to shutdown the main thread via `thread.interrupt_main` (which raises a `KeyboardInterrupt`)
- @keymone, in #516, moved `reactor.run` and signal handlers around, which prevented us from properly handling signals ourselves.
- Instead of explicitly setting signal handlers, he opted to use `signal.sigwait`, which blocks the main thread until a signal is received. However, if a `KeyboardInterrupt` is thrown (say, by pymesos), it is never translated to a `SIGINT` because the main thread is blocked. In some ways, this defeats the purpose of using `signal.sigwait`.
- Although the intent was to prevent reactor shutdown before state changes complete and are saved, @qui and I found that, through testing, this wasn't …
=> Prevent Pymesos thread abort from interrupting main thread

tests/bin/check_tron_jobs_test.py, tron/bin/check_tron_jobs.py
- Fixing a small bug in check_tron_jobs.py where I wrote it to `remove` instead of `discard` the precious attribute when converting the monitoring fields to Sensu args.
- Added a test to catch it.
- make dev (and run the patched script on a test job)
- make test
=> Fix check_tron_jobs to discard instead of remove precioius attr

tron/trondaemon.py
It logs "Got signal None" every time it goes through the loop...
You were right, it should be after the conditional. We only block the signals in the signal map, so we're only going to get those anyway.
=> Don't log other signals

contrib/migration_script.py
The push plan:
-  make a branch and do the yelpsoa-configs change
-  get ship it from the team
-  run this script, something like "./migration_script.py /nail/home/chl/yelpsoa-configs/tron/mesosstage/test2.yaml --server=http://tronplayground-uswest1adevc.dev.yelpcorp.com:8089 --old-ns=test2  --new-ns=test"
-  the script should wait with the message "Merge and push yelpsoa-configs branch. Ready to continue? [y/n]"
- merge yelpsoa-config branch
- enter 'y' to continue this script
This script does these things:
- read the source file to get the list of the jobs
- check if all jobs are not running
- disable all jobs
- stop cron
- wait for the yelpsoa-configs merge
- rsync yelpsoa-configs
- tronctl move each job
- update the new namespace
- update the old namespace
- start cron
=> add migration namespace script

dev/requirements.txt, tron/core/job_scheduler.py
Manually testing on my dev box. After "tronctl move test1.test test2.test", all runs for test1.test would be named as test2.test.[number]. https://fluffy.yelpcorp.com/i/t03slj07PwVkq49q7n9rnHM4jdWv60nQ.html
To resolve the page, we can do:
1. make a release
2. move the affected jobs to the old namespace through tronctl
3. move them back to the new namespace through tronctl
=> rename all job_name after migration

dev/requirements.txt, tests/bin/check_tron_jobs_test.py, tests/bin/get_tron_metrics_test.py, tox.ini, tron/bin/get_tron_metrics.py, tron/commands/client.py
- In #559, @qui added a generic metrics endpoint. This script pulls metrics from that endpoint and sends them to meteorite via its bash interface (so we don't need to import it). 
- The script is intended to be run as a cron job.
- manual testing with bogus metrics + dry-runs
- make test
- Should I be adding docs for this? I'm thinking not since this is rather Yelp specific.
- Too many tests? I just added that amount just in case things change later on.
- pre-commit was pinned because it was, at the time of writing, changed recently to use importlib_resources but there aren't wheels available for them yet.
=> Add get_tron_metrics script and tests

tron/scheduler.py, tron/utils/trontimespec.py
This changes existing behavior in one way: if you have a timezone set, the trontimespec used to always schedule for the second hour in the ambiguous case. Now, it will schedule for the first.
I tested this pretty extensively on playground by changing the system clock. Now in all cases, whether or not there is a timezone set, jobs will run in the first 1AM hour, and not the second 1AM.
e.g. on November 4th, a job that runs every 30 min would run at:
=> Combine DST code into one place

.gitignore, tron/commands/display.py
This is the "easy" part, but I think we need to be careful what we wish for.
This also "unsorts" the big `tronview` list. I think I kinda want that sorted?
But the bigger issue is that "the order on disk" is not what users think it is. This is because tronfig re-serializes the content into yaml *again* before posting. 
This PR is only half of the puzzle, because what the user actually needs is this *plus* us not sorting the yaml when we post. To do that, we'll need a different yaml library or some workarounds:
https://stackoverflow.com/questions/16782112/can-pyyaml-dump-dict-items-in-non-alphabetical-order
I could be convinced in either direction about what we should do (including no-ship).
=> Don't display actions/jobs in sorted order in tronview

.gitignore, bin/trond, bin/tronrepl, contrib/sync-from-yelp-prod.sh, debian/tron.service, docs/man/trond.8, docs/man_trond.rst, docs/tutorial.rst, example-cluster/start.sh, example-cluster/sync-from-yelp-prod.sh, tests/trondaemon_test.py, tests/utils/flockfile_test.py, tron/trondaemon.py, tron/utils/flockfile.py
- In the event of an unclean shutdown, Tron's pidfile and manhole socket could be left behind in the working directory, preventing another Tron daemon running, despite there being no existing daemon. However, these changes will allow us ignore those orphaned files and start Tron regardless.
- `tron.pid`:
- If we find a pid file and verify no process is running with that pid, instead of exiting, we now simply clear it out and continue on.
- We do not delete it, as we have already acquired a lock on it.
- `manhole.sock`:
- If `manhole.sock.lock` was also left behind after an unclean shutdown, Tron is already able to reclaim the lock and start with no problems.
- However, if the lock file was removed but the socket file remains, Tron would previously refuse to start. Now, the Tron daemon …
=> Allow tron to run after unclean shutdown

example-cluster/tronfig/MASTER.yaml, tests/core/actionrun_test.py, tests/core/jobrun_test.py, tron/config/config_parse.py, tron/config/schema.py, tron/core/action.py, tron/core/actionrun.py, tron/core/jobrun.py
- add trigger_timeout attribute to action, defaulting to None
- add trigger_timeout_timestamp attribute to actionrun, initialized in action run factory from job's run_time
- transition  to failed state when trigger_timeout passes and there are still triggers pending
bonus:
- add names to special exit codes, we'll maybe use them in UIs later
=> Trigger timeout attribute

tests/core/actionrun_test.py, tron/core/actionrun.py
Before, we had decided that we shouldn't retry if an action becomes unknown, because it means we've lost the connection and we don't know enough to retry. 
With Mesos, actions become unknown if we get a TASK_LOST update for them. In most cases, TASK_LOST means the agent running the task was terminated, and we should retry. It's possible that we get TASK_LOST for a task that is still running, in the case of a network partition, but I think if an action has automatic retries configured, they should be resilient to at-least-once execution anyway. 
This is kind of the same as losing an SSH connection, but... it didn't make sense to me to tell people that they would need to manually retry these cases, if it's going to be common with spot fleet. Thoughts?
=> Allow TASK_LOST updates to retry automatically

tests/core/actionrun_test.py, tron/core/actionrun.py
`handle` doesn't even exist, the attribute is called `handler`... added a test for it.
I actually can't use the handler anyway because it wants an ActionCommand to be passed in.
We can make both starting and running actions unknown because recovery will be looking for unknown actions and transitioning them to failed if they didn't start, anyway.
=> Fix start bug

.gitignore, tests/bin/get_tron_metrics_test.py, tron/bin/get_tron_metrics.py
- Added a `cluster` option to the `get_tron_metrics` script
- In the script, we forward the `cluster` value as a dimension in all Tron metrics we send to meteorite
- dry-run for metrics script
- make test
=> Add cluster option to metrics script

tron/core/job_scheduler.py
I've reproduced the bug and tested the fix at tron-mesosstage
=> Don't schedule jobs if they are disabled when renaming namespace

tests/trondaemon_test.py, tron/trondaemon.py
- Overall, fixed Tron daemon to allow serial signal handling
- Call `pthread_sigmask` before any threads are spawned so that we don't have a situation where some threads block on signals and others do not
- Remove pymesos SIGINT handler wrapper (no longer needed given `pthread_sigmask` change)
- Set SIGINT handler to an 'ignore' handler (not `signal.SIG_IGN`, which is an int, since the handler must be callable, given `interrupt_main`'s unstoppable interrupt)
- make test
- Manual testing against pymesos errors to ensure main thread does not also die
- Manual testing on mesosstage to verify SIGTERMs are being handled properly (not via signal handler)
**WARNING: The notes are long and comprehensive to help everyone fully understand the issue, since it has caused headaches for all of us.**
To …
=> Fix signal handling in tron daemon

tron/mesos.py
First step to making LOST updates more informative. 
Considering making taskproc partition-aware so we get task dropped/unreachable/gone instead of lost, but this is an easy first step.
http://mesos.apache.org/documentation/latest/task-state-reasons/
=> Log more information from terminal Mesos events

dev/config/MASTER.yaml, tests/serialize/runstate/statemanager_test.py, tron/serialize/runstate/statemanager.py
- Add a consistency check after loading state during startup to save it immediately after
- Failing to save would indicate corruption
- manual testing
- make test
- I'm not sure how much this protects us, since I haven't been able to generate a Tron bdb state file that can load but not save.
- Additionally, this check doesn't really protect us while Tron is running, i.e. Tron's running state gets corrupted and doesn't save.
=> Add consistency check on Tron startup

contrib/migration_script.py, tron/core/job_scheduler.py
I noticed that when the job is reconfigured, it would be rescheduled even if they are disabled.
Test this at playground.
This also contains the updating for migration script.
=> job should not be rescheduled when reconfiguration if it is disabled

tests/core/actionrun_test.py, tests/mesos_test.py, tron/core/actionrun.py, tron/mesos.py
There was a bug in logging terminal events that don't come from Mesos, so the task didn't exit. (Introduced in https://github.com/Yelp/Tron/pull/590.) I moved the logging code to `log_event_info` (which we wrap with a try-except to prevent logging from messing up state transitions) and check that the event is from Mesos before assuming event.raw will be a dict.
After the task exits with FAILSTART and a non-zero exit code, the action run handler should also fail. I changed exit_unsuccessful to transition to unknown if the exit status is None, instead of always failing, in https://github.com/Yelp/Tron/pull/581.
Manually verified this works for offer timeouts by running an action with an invalid pool, which will always lead to an offer timeout. The action fails.
=> Mesos action run should fail if it gets an offer timeout event

tests/core/actionrun_test.py, tests/mesos_test.py, tron/core/actionrun.py, tron/mesos.py
Now `self.fail_unknown` uses _done, which adds an end time and does other cleanup. The only place we don't to add an end time is when we're restoring an ActionRun from state and we're getting it ready for recovery, so I do the transition to unknown directly there.
In tron/mesos.py, we don't want to exit the tasks (and therefore give them an end time) when we're shutting down normally. `fail_tasks=True` is for when we're toggling Mesos off in an emergency, without shutting all of Tron down.
=> Set an end time if and only if the action should not be recovered

tron/default_config.yaml
These defaults don't allow tron to start automatically on freshly bootstrapped clusters.
This means they won't even get the API running enough for us to "post" the *actual* config.
This should make it so new tron servers can launch for the first time, without manual intervention, and let the cron jobs take over.
=> Don't try to use an ssh-agent for the default config

debian/tron.default, debian/tron.service
We need the option to pass arbitrary options to tron on systemd-based distros.
Specifically I need to set the listen port.
This also adds the generic "OPTS" var so that users can add new cli options that are not baked into the defaults file (without editing the .service file)
=> Allow passing extra options to systemd-based distros.

requirements.txt, tests/mesos_test.py, tron/mesos.py
Found several frameworks that had become inactive in prod. From nova-prod:
```
File "/opt/venvs/tron/lib/python3.6/site-packages/task_processing/plugins/mesos/execution_framework.py", line 345, in launch_tasks_for_offer
md = self.task_metadata[task.task_id]
File "/opt/venvs/tron/lib/python3.6/site-packages/pyrsistent/_pmap.py", line 71, in __getitem__
return PMap._getitem(self._buckets, key)
File "/opt/venvs/tron/lib/python3.6/site-packages/pyrsistent/_pmap.py", line 68, in _getitem
raise KeyError(key)
KeyError: 'paasta-contract-monitor.nova-prod-mesos.709.sleep.112a8604-e348-471c-9b7c-8afcb4019a07'
```
which looks like the task_metadata bugs (see TASKPROC-217).
I attempted to restart the framework by disabling and renabling Mesos, but that didn't work without L521 (in L323, a cancelled …
=> Fixes for inactive framework

tests/core/recovery_test.py, tron/core/recovery.py
After recovery, SSH actions are never unknown - the recovery has either succeeded or failed. However, Mesos actions may still be unknown, if we get a LOST update for it. We don't want to try to recover it again next restart (which resets the end time, etc), so we check if there's an end_time already.
This needs to be released after https://github.com/Yelp/Tron/pull/597, which updates the end times for Mesos actions correctly.
=> Only recover unknown Mesos actions that have no end time

tests/core/recovery_test.py, tron/core/recovery.py
Ticket TRON-584.
Error during startup:
```
tron.trondaemon _run_mcp:163 Error in configuration /nail/tron/config/: 'NoneType' object is not iterable
File "/opt/venvs/tron/lib/python3.6/site-packages/tron/trondaemon.py", line 160, in _run_mcp
self.mcp.initial_setup()
File "/opt/venvs/tron/lib/python3.6/site-packages/tron/mcp.py", line 63, in initial_setup
self.config.load().get_master().action_runner
File "/opt/venvs/tron/lib/python3.6/site-packages/tron/mcp.py", line 148, in restore_state
self.jobs.restore_state(states.get('job_state', {}), action_runner)
File "/opt/venvs/tron/lib/python3.6/site-packages/tron/core/job_collection.py", line 69, in restore_state
self.jobs[name].restore_state(state, config_action_runner)
File …
```
=> Skip job runs with no action runs during recovery

tests/core/actionrun_test.py, tron/core/actionrun.py
Before, if we were submitting a retry of a MesosActionRun, that action run already had a self.mesos_task_id corresponding to the previous attempt, so the new attempt would re-use that ID.
This makes None the default task ID for _create_mesos_task, and only passes in self.mesos_task_id when we are recovering.
=> Don't pass in task id when submitting retries of mesos actions

docs/command_context.rst, tests/utils/timeutils_test.py, tron/utils/timeutils.py
new date format to  correctly declare monthly dependencies with arithmetic
`{ym}` -> `2019-01`
`{ym+1}` -> `2019-02`
`{ym-1}` -> `2018-12`
=> Add ym format

tests/core/jobrun_test.py, tests/mcp_reconfigure_test.py, tron/core/actionrun.py, tron/core/jobrun.py
`is_<state>` checks on jobruns are proxied directly  to actionrun collection and are not always consistent with value of jobrun.state. This PR replaces proxying of `is_<state>` checks with a more direct  comparison to `state` property value.
=> Fix inconsistency between JobRun state attribute and is_<state> checks

bin/tronctl
Prints "client" and server versions, warns and  exits non-zero on mismatch.
=> Add tronctl version subcommand

tron/bin/check_tron_jobs.py
We'll need to fix it later. Job doesn't get start time if root action is waiting on external dependency.
=> Ignore duration=None for jobs waiting on external dependency

yelp_package/itest_dockerfiles/mesos/Dockerfile
as with https://github.com/Yelp/paasta/pull/2146, there isn't a mesos 1.7.2 package yet in the mesosphere apt repo.  I'll check back for that next week.
=> use mesos 1.7.1 in itests

docs/jobs.rst
- A lot of devs still expect the old behavior, so I'm updating the docs to say that any fields that aren't included in their job monitoring will default to those in `monitoring.yaml`.
=> Add docs for monitoring defaults

tron/core/actionrun.py
Realized my previous change was not rollback safe. If things end up in the waiting state, and then we need to roll back, it's impossible to transition the "waiting" actions to anything, since the state is unknown. 
With this, nothing can go to the waiting state, but it's safe to roll back to.
=> Add waiting state first for rollback safety

tests/core/actionrun_test.py, tests/core/job_test.py, tests/core/jobrun_test.py, tron/core/actionrun.py, tron/core/job.py, tron/core/jobrun.py
We need to differentiate between "waiting for dependencies" and "waiting for the previous job run to finish". QUEUED was being used for both, but now I'm proposing WAITING for the first state and QUEUED for the second. The key change is in L177 of tron/core/actionrun.py.
https://github.com/Yelp/Tron/pull/611 attempted to make "waiting for dependencies" into the RUNNING state, but that makes it seem like it's running as soon as its scheduled time has passed. That causes these issues:
* In the run_job callback that gets called when the scheduled time comes, it won't start the run if it's not "SCHEDULED". With #611, it already appeared running, so job_run.start() never got called. https://github.com/Yelp/Tron/blob/f115e9502153de09dc36f93d2bbbf303a35bb606/tron/core/job_scheduler.py#L130 
* …
=> Waiting state if an action is waiting for normal or cross-job dependencies

tests/mesos_test.py, tron/mesos.py
The CommandExecutor sends a TASK_STARTING state as of Mesos 1.5. http://mesos.apache.org/documentation/latest/upgrades/#1-5-x-task-starting
Wasn't an error before, but fills up the logs with this:
```
2019-03-21 15:58:27,696 tron.mesos.MASTER.testjob0.8.zeroth INFO Did not handle unknown 
type of event: Event(timestamp=1553209107.5581896, success=None, kind='task', 
terminal=False, message=None, platform_type='starting', extensions=pmap({}), 
task_id='MASTER.testjob0.8.zeroth.679f1ab0-425e-46a0-8c17-b514d55717a2', raw={'task_id': 
{'value': 'MASTER.testjob0.8.zeroth.679f1ab0-425e-46a0-8c17-b514d55717a2'}, 'state': 
'TASK_STARTING', 'source': 'SOURCE_EXECUTOR', 'agent_id': {'value': '6a8accd7-85ed-4c2b-
a09b-b92e8f3a48c2-S3'}, 'executor_id': {'value': …
```
=> Handle starting state from Mesos

tests/utils/timeutils_test.py, tron/utils/timeutils.py
- If `macro_timedelta` is given 03/30 and told to subtract a month from it, it will give 02/30, which is an invalid day. 
- I've made a change that rounds the day to the number of days in a given month if that day doesn't exist. So now, 03/30 becomes 02/28 (for non-leap years like 2019).
make test
=> Make macro_timedelta round days if day > a month's days

requirements.txt
@kawaiwanyelp someone needs to review this, and you also have some changes in this bump: https://github.com/Yelp/task_processing/commits/master
Look reasonable?
=> Bump taskproc to 0.1.5 to include fix that restarts driver on error

debian/tron.service
Tron needs to be able to open enough files to deal with more jobs.
=> changed max number of open files to 10000

tron/core/jobrun.py
found this error a couple times in the logs with the latest version:
```
File "/opt/venvs/tron/lib/python3.6/site-packages/tron/api/async_resource.py", line 34, in process
result = fn(resource, request)
File "/opt/venvs/tron/lib/python3.6/site-packages/tron/api/resource.py", line 323, in render_GET
include_node_pool,
File "/opt/venvs/tron/lib/python3.6/site-packages/tron/api/resource.py", line 286, in get_data
num_runs=5,
File "/opt/venvs/tron/lib/python3.6/site-packages/tron/api/adapter.py", line 53, in adapt_many
adapter_class(item, *args, **kwargs).get_repr() for item in seq
File "/opt/venvs/tron/lib/python3.6/site-packages/tron/api/adapter.py", line 54, in <listcomp>
if item is not None
File "/opt/venvs/tron/lib/python3.6/site-packages/tron/api/adapter.py", line 42, in get_repr …
```
=> Just get run state once to reduce iterating on deque

tests/bin/check_tron_jobs_test.py, tron/bin/check_tron_jobs.py
- `check_tron_jobs` previously only checked the last 20 runs, using the min and max dates of those runs when the precious flag is set. However, if runs are out of order and a successful run for a checked date is older than the 20, the script will throw a false error.
- This change makes it so that `check_tron_jobs` looks at a job's entire history to fix the above problem. Given that we have a default maximum of 50 historical job, there shouldn't be a huge performance hit (it's just bucketing a few more things).
make test
=> Make check_tron_jobs look at entire history by removing count arg

tests/serialize/runstate/dynamodb_state_store_test.py, tests/serialize/runstate/mirror_state_store_test.py, tron/serialize/runstate/dynamodb_state_store.py, tron/serialize/runstate/mirror_state_store.py
1. Instead of reading num_partitions and then read contents one by one, it just fetch all partitions and read 100 at a time (limit of batch_get_item method).
Test done:
Tested on mesosstage.
=> Improve dynamodb read/write speed

tests/serialize/filehandler_test.py, tron/serialize/filehandler.py
`trond` is rarely segfaulting at random moments when running under heavy
load with Python 3.6.0.  It seems that the crash is caused by
`task_processing.plugins.mesos.logging_executor` writes into a closed
filehandler inside `FileHandleWrapper`, triggering
https://bugs.python.org/issue31976.
The bug is fixed in Python 3.7.x, but since we cannot migrate from 3.6.x
at the moment, let's add a workaround by protesting all filehandler
operations by a lock, avoiding the bug as the result.
=> Workaround for trond segfaults

tests/bin/check_tron_jobs_test.py, tron/bin/check_tron_jobs.py
A user reported that they weren't getting alerted immediately when an action became unknown in their job. I looked into it, and saw that the job run was in the "waiting" state. This can happen when a job run has one action waiting for a cross-job dependency while the other action has failed.
=> Check for failed or unknown action if a run is waiting

docs/config.rst, docs/jobs.rst, docs/overview.rst, docs/tron.yaml, docs/tutorial.rst
I marked interval scheduler as removed and change all examples using interval scheduler to use cron. I used version 0.9.12.6 which would be the version of the next release.
=> "Remove" interval scheduler from documentation

dev/config/MASTER.yaml, tron/core/actionrun.py, tron/core/jobrun.py
Once we have this, we can set up a log handler to pull these into a separate log and ingest them wherever we want.
Some example lines:
```
{"id": "MASTER.testjob1.8.first", "type": "SSHActionRun", "state": "running", "timestamp": 1555533995.7740123}
{"id": "MASTER.testjob0.8.zeroth", "type": "SSHActionRun", "state": "unknown", "timestamp": 1555533996.7385292}
{"id": "MASTER.testjob0.8", "type": "JobRun", "state": "unknown", "timestamp": 1555533996.7392828}
```
=> Log state changes

tests/api/controller_test.py, tron/api/controller.py
tested on my devbox and on mesosstage
One thing I noticed is that if the config file in /nail/tron/config/whatever.yaml has a bad value, tron can't restart.  That's probably a different issue, but maybe something worth fixing?
=> reload old config if new config fails

tests/api/resource_test.py, tron/api/resource.py
We were setting the code to `None` if the response was not a dict, causing this:
```
Apr 25 17:19:16 tron1-uswest1bprod tron: CRITICAL pid=20629 tid=140564817245952 twisted publishToNewObserver:154 
File "/opt/venvs/tron/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
result = inContext.theWork()
File "/opt/venvs/tron/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
File "/opt/venvs/tron/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
return self.currentContext().callWithContext(ctx, func, *args, **kw)
File "/opt/venvs/tron/lib/python3.6/site-packages/twisted/python/context.py", line 85, …
```
=> Return 200 if no code is passed and the response is not a dict

tests/bin/check_tron_jobs_test.py, tron/bin/check_tron_jobs.py
Tron does not realert as expected after Tron jobs fail when no run ever starts. Check TRON-1104 for detail.
I updated tron such that it checks run_time when no start_time exists. No start_time exists when the job never runs. run_time is the scheduled time of the job.
=> Fixed guess_realert_every

.gitignore, Makefile, tron/core/recovery.py, tron/node.py
If the recovery action fails, then the state of the action should be unknown, not failed, because we don't know what happened to the real action command.
Internal ticket TRON-1116. 
This just affects the logic in the handler: https://github.com/Yelp/Tron/blob/a068fe84474cf2a51b72ad31b98c1df419ea6d98/tron/core/actionrun.py#L742
Before this change, if the recovery command failed to connect, the ActionCommand would emit the FAILSTART event, which Tron thinks is safe to retry because nothing has happened yet. After this change, if it fails to connect, it emits a EXITING event with `exit_status=None`, which triggers `fail_unknown` as desired.
I tested this manually:
1. let a run start
2. shut down Tron
3. edit the node config for localhost with a different user (e.g. `user: batch`) so SSH …
=> Prevent a connection error in the recovery action from failing the action

tests/serialize/runstate/dynamodb_state_store_test.py, tron/serialize/runstate/dynamodb_state_store.py
The index is sorted as str rather than int. So when there are more than 10 partitions, the data is merged in wrong order. 
I also updated test to cover this case.
=> Changed dynamodb partition index to int so it is sorted correctly

tests/bin/check_tron_jobs_test.py, tron/bin/check_tron_jobs.py
I tested with real data as well but didn't use it here since that is too long. 
The bug happens when run_time is the same as next_run, 1 is returned.
=> fix guess_realert when next_run is the same as previous_run

debian/tron.links
Stop using the compatibility dir and use the standard completion dir, introduced in bash-completion 2.x. Completion scripts in there are lazily loaded, which defers the ~180ms cost of invoking the completion registration.
=> Place the bash completion script in the completion dir

bin/tronctl_tabcomplete.sh, bin/tronview_tabcomplete.sh, debian/tron.links
bash-completion lazy loading loads the completion based on the executable name, so the name of the completion file needs to match. https://github.com/scop/bash-completion/blob/master/README.md
=> Split the tab completion file

tests/core/jobrun_test.py, tron/core/jobrun.py
If any run in a job is WAITING, the next job run will get queued (if allow_overlap is False, the default) because a WAITING run still counts as active. If there are actions waiting for a trigger, that's legitimate - the run really isn't done yet, and we shouldn't start the next one. But there have been two cases recently where the next run **doesn't** start as expected because a previous run is unexpectedly waiting, which I'm trying to fix in this PR. 
My solution is to say the overall run is WAITING only if an action is blocked on a trigger. It shouldn't have waiting actions that aren't blocked on triggers unless something has gone wrong, because we try to start unblocked actions as soon as they become unblocked.
1) One action A, required by B, goes unknown. No other actions in the job …
=> Prevent job runs from incorrectly getting stuck in WAITING

tests/bin/recover_batch_test.py, tron/bin/recover_batch.py, tron/core/recovery.py
If the action runner suddenly goes away, the status file might not receive a return code. In addition to watching for a return code, I've made the recovery script also check if the action runner is still around. If it isn't, we exit with a code 1.
make test (made a `recover_batch_test.py` file)
=> Make recovery batch script also check if action runner suddenly goes away

tests/core/jobrun_test.py, tron/core/jobrun.py
If a job isn't in a scheduled state when Tron tries to start it in the the job scheduler, it won't start: https://github.com/Yelp/Tron/blob/master/tron/core/job_scheduler.py#L130
Added some assertions about the scheduled state. test_with_trigger fails before the fix, passes after.
=> Runs with triggers should start in scheduled state

.gitignore, .travis.yml, yelp_package/bionic/Dockerfile
- Added `debian/.debhelper/` to `.gitignore` (and sorted the things under `debian/` for good measure)
- Start building for bionic (same `Dockerfile` as for xenial, but I removed the deadsnakes stuff since [bionic ships with python 3.6](https://packages.ubuntu.com/bionic/python3.6) and also removed the dh-virtualenv wget installation since [bionic ships with the same version, 1.0-1](https://packages.ubuntu.com/bionic/dh-virtualenv))
Testing:
- Ran `make itest_bionic` and it passed successfully
Is there anything else I should update? I didn't touch some of the stuff like [this](https://github.com/Yelp/Tron/blob/ba6eee0094101e0a8b26dd6e66f5ca6ccb0ca3f7/Makefile#L67-L78) since it doesn't really affect building an actual tron bionic package.
=> Build for bionic

tests/core/job_scheduler_test.py, tests/core/job_test.py, tests/mcp_reconfigure_test.py, tron/bin/recover_batch.py, tron/core/job_scheduler.py
- When a job run is cancelled, Tron will schedule the next run after the cancelled run. However, if the  job is reconfigured , there is a bug that makes it so that the recreated scheduled run is instead scheduled to run at the same time as the cancelled job.
- To fix this bug, I have made it so that when recreating the scheduled run, Tron copies the existing the scheduled run's run time to the new scheduled run, thus preserving the correct time.
manual testing with `make dev`
`make test`
=> Preserve last run's scheduled time when reconfiguring

tests/core/job_test.py, tron/core/job_scheduler.py
Regression introduced here: https://github.com/Yelp/Tron/pull/674/commits/dedb5a93ded5fd232f9bf216be2e37ff6d076968#diff-c5160fb364ea48a71d54f9eec62ff1a0L195
There were some noop "assertions" in the tests, fixed them to be real assertions.
=> Use last run time to get next run time before scheduling

tests/bin/recover_batch_test.py, tron/bin/recover_batch.py
There seems to be a race condition in which the pid can become None before the recover_batch process can read it, causing this traceback:
`['Traceback (most recent call last):', '  File "/opt/venvs/tron/bin/recover_batch.py", line 108, in <module>', '    run(args.filepath)', '  File "/opt/venvs/tron/bin/recover_batch.py", line 86, in run', '    if not psutil.pid_exists(runner_pid):', '  File "/opt/venvs/tron/lib/python3.6/site-packages/psutil/__init__.py", line 1502, in pid_exists', '    if pid < 0:', "TypeError: '<' not supported between instances of 'NoneType' and 'int'"]`
I am adding a check that the pid cannot be None. If it is, we assume the runner was terminated.
make test
=> Determine that runner is not running anymore if pid is none for recover_batch

tests/mesos_test.py, tron/mesos.py
TRON-1185: some actions were finishing successfully with TASK_FINISHED but end up in the "failed" state because we missed the starting update.
Still don't know why we are sometimes missing the starting update, but it doesn't hurt to call `self.starting()` twice (once for STARTING, once for RUNNING).
=> Use starting update from Mesos

docs/jobs.rst, tests/command_context_test.py, tests/config/config_parse_test.py, tests/config/schedule_parse_test.py, tests/data/test_config.yaml, tests/scheduler_test.py, tests/trond_test.py, tron/config/schedule_parse.py, tron/scheduler.py, tronweb/coffee/job.coffee
I have a review out to remove the last usage of this scheduler, so I'm feeling ambitious.
Just like we removed tron services, I don't think tron should be used to "constantly" schedule something.
=> Removed the constant scheduler

tests/bin/check_tron_jobs_test.py, tests/commands/cmd_utils_test.py, tron/bin/check_tron_jobs.py, tron/bin/get_tron_metrics.py, tron/commands/client.py, tron/commands/cmd_utils.py
I don't feel great about this, but I think we need to have cluster_name in two places:
1. In the client somehow so we can sprinkle it in places like this
2. In the server object (mcp) so it can be used as a global variable in many places.
This is part 1.
=> Use a cluster_name attribute for check_tron_jobs and metrics

tests/bin/check_tron_jobs_test.py, tron/bin/check_tron_jobs.py
3 changes to speed things up:
1. Don't called `client.index()` over and over again
2. Don't make a 2nd call to `client.job()` to get the specific job run -- we already have that info from what I can tell (but someone should check me on that)
3. Only get `client.action_runs()` if the job failed (this the is the big one)
On my dev box this takes running `check_tron_jobs` from ~4.5min to ~45 seconds.
See TRON-1385 for details
=> Speed up check tron jobs

Makefile, dev/config/MASTER.yaml, example-cluster/tronfig/MASTER.yaml, tron/core/actionrun.py
I don't know if this is the best solution, but it does seem to do the trick. (tested with `make dev`)
=> Don't do a retry_delay when manually retrying a failed command.

tron/bin/check_tron_jobs.py
The previous method was returning a `TronObjectIdentifier` namedtuple, resulting in alerts referencing jobs called things like `TronObjectIdentifier(type='JOB_RUN', url='/api/jobs/jolt.gc_zookeeper/32780')`.
For comparison:
```
(Pdb) relevant_job_run['id']
'ahab.update_docker_repositories.40088'
```
=> fix job run ids reported by check_tron_jobs

tests/bin/recover_batch_test.py, tron/bin/recover_batch.py
While testing recovery, I found that recovery was hanging forever. There are a few bugs, which I'll do in separate PRs.
First, both read_last_yaml_entries and get_key_from_last_line were only loading part of the status entry, e.g. `{'timestamp': 1569013680.5727654}`. From pyyaml 3.11 to 5.1, they changed `default_flow_style` from True to False. With True, each status entry is in one line, while with False, each key is in a separate line:
```
>>> yaml.safe_dump({'a': 1, 'b': 2}, explicit_start=True, default_flow_style=True)
'--- {a: 1, b: 2}\n'
>>> yaml.safe_dump({'a': 1, 'b': 2}, explicit_start=True, default_flow_style=False)
'---\na: 1\nb: 2\n'
```
Now I'm using yaml.load_all to parse it for us instead of assuming things about the lines. That should work with either flow style.
=> Fix YAML doc loading

tests/bin/recover_batch_test.py, tron/bin/recover_batch.py
I didn't catch this in stage because I think we only had short-running jobs there that already picked up the action_runner file-closing fix (https://github.com/Yelp/Tron/pull/694) before my restart. This bug happens when an SSH action starts with an old version (1.0.1) but is recovered with the new version (1.0.4).
```
File "/opt/venvs/tron/bin/recover_batch.py", line 101, in <module>
run(args.filepath)
File "/opt/venvs/tron/bin/recover_batch.py", line 81, in run
return_code, error_message = get_exit_code(fpath)
File "/opt/venvs/tron/bin/recover_batch.py", line 70, in get_exit_code
log.warning(f"Status file {filepath.path} didn't have a PID. Will watch the file for updates.")
AttributeError: 'str' object has no attribute 'path'
```
plus a minor logging …
=> Incorrect type in logging message

tests/core/actionrun_test.py, tests/core/recovery_test.py, tron/core/actionrun.py, tron/core/recovery.py
I tested this with `make dev` locally.
I (or someone else) can follow up with the actual retries later, wanted to keep the diff small to reduce the chance of mistakes 😬
=> Move SSH action recovery logic into the class to enable retries

bin/tronctl, tests/api/controller_test.py, tests/core/actionrun_test.py, tron/api/controller.py, tron/core/actionrun.py
Now that both SSH and Mesos actions have a recover method, recovery can be a first-class command. Now the wiki for handling unknown action runs can just say "run tronctl recover".
The next step is to make recovery automatic, but this was a simple first step.
=> Add manual recovery command to api

tests/core/actionrun_test.py, tron/core/actionrun.py
Yesterday the docker daemon on a batch box got stuck and many actions never "completed" just because the container didn't exit. A user saw that their action had already produced a COMPLETE file and used `tronctl success` to finish it. Once I got around to restarting the docker daemon, the process finally exited and triggered a retry, which is bad because the retry cleared the s3 output directory and dependencies had already started running.
Most of the tests I just moved around because I thought they should go in the general ActionRun test rather than the SSHActionRun test, but test_auto_retry_already_done is the one that covers this case.
=> Do not auto retry action if state is already succeeded

tests/bin/check_tron_jobs_test.py, tron/bin/check_tron_jobs.py
I think this handles the issues we've been seeing, where a backfill causes erroneous alerts.
I reversed the order of the runs in the test to match the Tron API - it returns newest runs first.
=> Try to handle backfills better in monitoring precious runs

tests/bin/check_tron_jobs_test.py, tron/bin/check_tron_jobs.py
The stderr in the output of Tron checks can be obnoxiously big and usually does not actually contain output from the task itself, but rather Mesos. This adds an setting to turn it off.
=> Added an option to hide stderr from checks

tron/bin/check_tron_jobs.py
This fixes the issue where DST happens and then we think that "today" hasn't happened yet because adding the step brings the `start` variable to a time in the future.
Feature request: can we use `arrow` in Tron?  It supports these types of interval constructions natively (though I guess I haven't actually tested to see if it handles this edge case correctly)...
=> fix time interval construction in check_tron_jobs

dev/config/MASTER.yaml, tests/core/job_test.py, tron/core/job.py
It's a little more complicated than _just_ adding to the equality list because the run_limit is a property of the JobRunCollection.  I couldn't think of a cleaner way to do this, but it's possible one exists.
=> run_limit changes are picked up by tronfig

dev/config/_manifest.yaml, tests/config/manager_test.py, tests/core/jobgraph_test.py, tron/config/manager.py, tron/core/jobgraph.py
This makes sure user cannot change the name of a job/action which is
triggered/required by other actions and have things silently fail.
=> Enforce job graph dependency

tests/core/job_test.py, tests/core/jobrun_test.py, tron/api/adapter.py, tron/core/actionrun.py, tron/core/job.py, tron/core/jobrun.py
This will prevent issues like DAR-755 from happening again.  In summary, instead of storing things in `/nail/tron/namespace.jobname/namespace.jobname.run_num/namespace.jobname.run_num.actionname/.stdout` (and, when we have to recover an "unknown" action, `/nail/tron/namespace.jobname/namespace.jobname.run_num/namespace.jobname.run_num.actionname/namespace.jobname.run_num.recovery-namespace.jobname.run_num.actionname/.stdout`), we instead store things in `/nail/tron/namespace/jobname/run_num/action_name/.stdout` or `/nail/tron/namespace/jobname/run_num/action_name-recovery/.stdout`.  Aside from keeping us from running into the 255-char pathname limit, this also will help organize things on our Tron masters a little more sanely.
**Testing Done**
* `make test` passes
* manual testing with …
=> tron output dir names shortened

tests/config/manager_test.py, tron/config/manager.py
Tron does not natively support cross-cluster triggers right now. The temporary workaround is using `tronctl publish` to expose cross-cluster triggers. Such dependency is hard to capture and can break tron config writes at pre-write validation step if existing configuration already contains such dependency.
This PR is a short-term fix which turns off job graph validation for config writes. A longer-term solution is adding a flag to rule out certain actions from job graph validation. Eventually we will turn job graph validation back up after tron natively support cross-cluster triggers.
=> Skip job graph validation in write_config

tests/utils/trontimespec_test.py, tron/utils/trontimespec.py
We found that hourly jobs were running again and again with 1AM
as their run time after fall forward.
This was TRON-949 - it's not great because periodic jobs like p-c-m will run continuously, increasing load on the Tron masters.
I am pretty sure this fixes it - the test fails before the change, with `result.hour` equal to 1. After the fix, the hour is 3, as expected.
=> Fix bug from fall forward last year

tronweb/coffee/graph.coffee
This change allows users to pin a node, move it around, and unpin the node using double-click. It does so by making the node fixed on `dragstart` event, and making it un-fixed on `dblclick`
It allows users to arrange the tronweb dependency graph to stay **static** once organized, instead of moving to a random state even when users try to organize nodes.
Manually tested by adding more nodes and dependencies in the tronfig and then arranging the tronweb dependency graph.
Note: This change however does not automatically organize the graph to a left-to-right looking DAG, that can be an additional improvement later.
=> Pinning nodes in tronweb dependency graph to make it look sane

tron/core/job_scheduler.py
Don't force state save if no runs were scheduled.
=> Remove unnecessary state change

tron/ssh.py
Tron uses twisted ssh to do ssh to batch hosts for `executor: ssh` jobs. Tron currently specifies `publickey` as the only supported AuthenticationMethod via the `NoPasswordAuthClient` class definition. As such, tron is unable to ssh to hosts that have been configured to use PAM as a "second factor" beyond ssh keys for ssh authorization. 
For context, I'll give additional details here about how we're using PAM. Typically PAM is used in a way that is actually interactive with the end-user, e.g. the user has to enter a TOTP passcode or type an additional password. This is why PAM requires the `keyboard-interactive` authentication method. In our case, we actually don't require interaction with the end user. Our PAM module evaluates a set of policies to make an `allow` vs `deny` decision based …
=> Support keyboard-interactive as an authentication method for ssh

tron/ssh.py
if there is no actual reason to prompt the user (e.g. there is a keyboard-interactive authentication mechanism, but there is no actual input taken from the user)
Realistically, this fix should go in twisted itself (in https://github.com/twisted/twisted/blob/trunk/src/twisted/conch/client/default.py#L300), but that is more 🐰🕳️than I want to deal with right now and I'd like to see if this works first before trying to push that upstream.
I think this will work around the issue described in TRON-1531, but really the best way for me to verify that is to try deploying this on one of the tron masters in devc (or hot patching it directly). Open to suggestions for other approaches or other testing strategies. See TRON-1531 for details.
=> TRON-1531: Suppress the need to prompt the user via tty

requirements.txt
(COMPINFRA-333) The task_processing library handled LIKE constraints
using a "match" expression instead of a "fullmatch" expression, which
meant that "pool: stable" jobs would get scheduled on the stable_batch
pool.  This version bump fixes that behaviour.
=> Bump requirements to pick up new task_proc version

.pre-commit-config.yaml, bin/tronctl, cluster_itests/steps/itest_utils.py, tests/api/controller_test.py, tests/core/actionrun_test.py, tests/serialize/runstate/dynamodb_state_store_test.py, tests/trond_test.py, tron/mesos.py, tron/serialize/runstate/dynamodb_state_store.py
TRON-1539: adding some observability to help us debug.
1. Add log line for every save failure
2. Add some timing metrics so we can see if individual operations are taking longer. These show up when you curl `/api/metrics` and represent an exponentially decaying sample. We already have a cron job that periodically curls this endpoint and puts all the metrics into signalfx.
3. Fix the tests so they actually fail when setitem and delete_Item raise exceptions. _consume_save_queue catches all exceptions and just logs and increments save_errors, and the delete test wasn't calling delete_item at all before because you can only iterate through the `pairs` iterator once.
Metrics example:
```
{
"counter": [],
"gauge": [],
"histogram": [],
"meter": [
{
"name": "tron.site.2xx",
"count": 1,
"m1_rate": …
```
=> Tron 1539 dynamo metrics

tron/serialize/runstate/dynamodb_state_store.py
While working on refactoring the state (TRON-1527), I noticed that a lot of events were being saved to dynamodb, even with a single test job. We are writing to dynamodb for every state change - it should be enough to save the latest value for a key in the buffer.
I expect OrderedDict.popitem() to be similar in terms of perf to the deque because it's implemented with a doubly-linked list: https://github.com/python/cpython/blob/3.6/Lib/collections/__init__.py#L71.
=> De-duplicate items in the DynamoDB save queue

tests/core/job_test.py, tests/core/jobrun_test.py, tests/serialize/runstate/dynamodb_state_store_test.py, tests/serialize/runstate/shelvestore_test.py, tests/serialize/runstate/statemanager_test.py, tests/serialize/runstate/yamlstore_test.py, tools/migration/migrate_state_1.3.15_to_1.4.0.py, tron/core/job.py, tron/core/jobrun.py, tron/serialize/runstate/__init__.py, tron/serialize/runstate/dynamodb_state_store.py, tron/serialize/runstate/shelvestore.py, tron/serialize/runstate/statemanager.py, tron/serialize/runstate/yamlstore.py
Here's the part that actually saves the job run state separately, based on the events added in https://github.com/Yelp/Tron/pull/758/files.
The diff is big because I needed to add support for delete to the state stores, otherwise old job run state would never get deleted.
This is not backwards compatible, so I wrote a script that can go back and forth. My upgrade plan is:
1) stop Tron, install new version
2) run the script
3) start Tron. if this doesn't work for whatever reason, run the script to migrate state back, then install the old version and restart.
I've tested this a bunch of times back in forth with a local dev cluster.
=> Tron 1527: save job runs separately in state store from job state

tox.ini
Trying this again.
---
This package is not available externally.
=> install clusterman-metrics from internal yelp pypi only

yelp_package/bionic/Dockerfile
I tested this locally and it seemed to fix it.  I'll re-enable the Jenkins build and test it there.
=> fix the bionic build by installing the right virtualenv for inscrutable reasons

tron/core/job_scheduler.py, tron/serialize/runstate/dynamodb_state_store.py, tron/serialize/runstate/statemanager.py
2 small changes that I combined into one review.
After the state migration, the logs are full of errors like
```
Aug 12 00:22:29 tron1-uswest2aprod trond[15510]: --- Logging error ---
Aug 12 00:22:29 tron1-uswest2aprod trond[15510]: Traceback (most recent call last):
Aug 12 00:22:29 tron1-uswest2aprod trond[15510]:   File "/usr/lib/python3.6/logging/handlers.py", line 914, in emit
Aug 12 00:22:29 tron1-uswest2aprod trond[15510]:     self.socket.send(msg)
Aug 12 00:22:29 tron1-uswest2aprod trond[15510]: OSError: [Errno 90] Message too long
Aug 12 00:22:29 tron1-uswest2aprod trond[15510]: During handling of the above exception, another exception occurred:
Aug 12 00:22:29 tron1-uswest2aprod trond[15510]: Traceback (most recent call last):
Aug 12 00:22:29 tron1-uswest2aprod trond[15510]: …
```
=> Tron logging errors

tests/bin/check_tron_jobs_test.py, tron/bin/check_tron_jobs.py
This covers the case where the initial actions start and complete, but then the job is waiting for triggers in later actions. This is described in the ticket TRON-1542.
I don't think we should alert in the case that no actions in the job have started (the TODO). job_run start_time (and therefore duration) is based on the start time of the first action. If we assumed run_time when start_time doesn't exist yet, the following could happen:
* run_time is 1 am, expected_runtime is 3 hours
* no actions have started by 4 am: alert
* action starts at 4:15: start time is now 4:15, duration is now < 1 min, alert resolves
If we wanted to solve it, we should change the way start_time gets calculated, not this script. In the meantime, a workaround if people want to be alerted in that case is setting a …
=> Alert for waiting jobs as long as other actions in the job have started

tron/bin/check_tron_jobs.py
Tested by adding check_oom_events to a job's monitoring and running the script -  pysensu fails to send the event without this change and succeeds after.
=> Skip check_oom_events key from monitoring, which is only used by paasta

tests/mesos_test.py, tron/mesos.py
We were leaking AWS creds in the stderr Mesos logs, this change redacts them.
=> redact AWS credentials from the logs

tests/api/controller_test.py, tests/core/job_collection_test.py, tests/mcp_test.py, tron/api/controller.py, tron/core/job_collection.py, tron/mcp.py
map_to_job_and_schedule does all the updating - this change reduces the number of jobs that it gets called on.
This should make setup_tron_namespace faster (TRON-1523), and reduce API slowness overall.
=> Only reconfigure jobs in that namespace when a namespace is updated

Makefile, tox.ini
without this, venv-update on a devbox will error on a rebuild of the
venv since basepython will be the python inside the venv, instead of the
canonical system one.
We set this globally through puppet internally - we don't need to do
this anymore.
This technically isn't breaking anything, but we might as well do it as
we modernize the codebase.
This will be unnecessary as soon as we roll out per-platform packade
indicies, but for now we still need p-c-p
=> Small Makefile/tox.ini updates

Makefile
This reverts commit b474d931859c68f6548e8f2daa62e352111e6131. 
Turns out I can't read and we were using this for itests as well.
=> Revert "Remove PIP_INDEX_URL shenanigans"

tests/core/actionrun_test.py, tron/core/actionrun.py
Previously, we used to emit triggers before we transitioned to the next state. However, this caused some confusion since the transition could be invalid (i.e. no next state to transition to). This change ensures that the transition is first valid before we can emit triggers.
`make test` - PASSED
=> Tronctl success no longer emits trigger when the transition is invalid

bin/tronctl, tests/api/controller_test.py, tron/api/controller.py, tron/api/resource.py
Skipping an action that has downstream triggers is error-prone as its easy to forget that you have triggers to emit and what triggers to emit. You prob need to go check your tronfig definitions to see what triggers exist and converting the trigger name to a trigger command can be a little tricky (with date magic).
To solve this, we add a new tronctl command that will skip an action and then publish all triggers for that action
Testing: mostly manual, there are no tronctl tests. `make test itest_bionic` pass, though!
=> Implementation of skip-and-publish

tests/config/config_parse_test.py, tron/config/config_parse.py, tron/config/schema.py, tron/config/tronfig_schema.json
We'll be adding two toggles to control Tron's usage of k8s:
* a global killswitch (`k8s_options["enabled"]`) for when we want to go
back to Mesos for an entire cluster (and, in the future, for when we
want to quickly stop all Tronjobs).
* a per-job opt-out (`use_k8s`) for any jobs that encounter issues with
k8s or that we want to migrate at a specific time.
Since I was adding a k8s config section to the Tron master config, I
also went ahead and added a way to configure what the k8s API address
should be (i.e., the "master" address).
=> Add initial k8s config + global k8s toggle + job opt-out

tron/config/schema.py
I somehow forget to include this in the PR that added support for k8s
toggles.
=> Add kubernetes as a valid ExecutorType

.github/workflows/ci.yml, tox.ini
This will make it so that JS-based pre-commit hooks will work regardless
of how you invoke our tox testenv.
=> install js dependencies in tox for use in pre-commit

mypy.ini, requirements-dev-minimal.txt, requirements-dev.txt, tox.ini, tron/kubernetes.py
* we have requirements-tools installed, but aren't automatically running
it
* we're starting to add types to new code, so let's have mypy
automatically check it instead of relying on our editor setups to run
it for us :p
=> Add check-requirements and mypy to our tox tests

tests/config/config_parse_test.py, tron/config/config_parse.py, tron/config/schema.py
kubeconfig files already contain the master address, so no need to
duplicate that here. additionally, we'll need to know what kubeconfig to
use, so lets replace master_address with kubeconfig_path
=> Store kubeconfig path in tron settings, not k8s master address

tests/config/config_parse_test.py, tests/kubernetes_test.py, tron/config/config_parse.py, tron/config/schema.py, tron/kubernetes.py
This mirrors how we handle default volumes on the mesos side, keeping it as an attribute in `KubernetesClusters` and applying the same to all clusters within a `KubernetesClusterRepository`.  Since we'll just be using the exact same source config for default_volumes, we're copying the config schema & validation logic as well.
Because we have not yet started implementing `create_task` to apply parameters to tasks, I haven't added that to this PR, but this should let us start handling a `default_volumes` key in our master config under `k8s_options`.
The tests are somewhat sparse here (just duplicating existing tests) since we don't *do* much based on this config, we just store it or set a default. Let me know if you think there should be more cases we want to test.
=> TRON-1625: Add handling for default volumes config at the cluster level

tests/kubernetes_test.py
In #819 , I added default_volume support to our `k8s_options`.  However, in the test, I specified our test list of `default_volumes` as a list of `dict` rather than the expected `ConfigVolume`.
This fixes the test so this does not mislead anyone in the future.
=> Fix kubernetes configuration tests to use correct default_volumes class

requirements-dev.txt, requirements-minimal.txt, requirements.txt, tests/kubernetes_test.py, tron/core/action.py, tron/core/actionrun.py, tron/kubernetes.py
We aren't yet reading any of the events that task_proc is bubbling back
up to us, but that'll come next.
With this, we should be giving task_proc all the information it needs to
actually create a usable Pod.
=> Enable submitting a task to k8s using task_proc

tests/config/config_parse_test.py, tron/config/config_parse.py, tron/config/config_utils.py, tron/config/schema.py
*Note*: This PR Is based off of #818. I will update when that is merged. 
With k8s jobs, we will be configuring environment variables from Kubernetes Secret resources.  To do this, we need to know the secret resources' names and keys.
This adds a new `secret_env` key to `TronActionConfig`, which will map an envvar to a `ConfigSecretSource`, whose keys (`secret`, `key`)  map to the required values of a Kubernetes [SecretKeySelector](https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#secretkeyselector-v1-core) (`name`, `key`).
This required adding a new dict validator to verify values of a dict passed an expected validator. The existing `build_dict_name_validator` presumed the type being validated had a `name` field, which is not the case for our …
=> TRON-1637: Add support for secret_env key on action configs

tests/core/action_test.py, tests/kubernetes_test.py, tron/core/action.py, tron/core/actionrun.py, tron/kubernetes.py
Once tronfig supports secret_env with #821, this change will use that config to relay to task_proc `KubernetesTaskConfig`'s `secret_environment`, which was added in https://github.com/Yelp/task_processing/pull/170
This continues the same pattern of converting from `Config*` classes to native dicts when we relay to `KubernetesTaskConfig` in `KubernetesCluster.create_task`, as we had been doing with `volumes` from #818
=> TRON-1627: Pass secret_env to taskproc from kubernetes

tests/kubernetes_test.py, tron/kubernetes.py
Tron now checks to see which state machine it will transition to with every new pod event. Pod events are based on the pod lifecycle phases.
`make test - PASSED`
=> TRON-1611 Handle KubernetesTask State Machine Transitions

requirements.txt, tests/kubernetes_test.py, tron/kubernetes.py
see https://github.com/Yelp/task_processing/pull/173 :p
=> Use un-typo'd failed platform_type for k8s events

Makefile, yelp_package/extra_requirements_yelp.txt
Currently, we aren't installing yelp-meteorite, which means that task-processing isn't emitting any metrics. I copied paasta's approach and made it so that when we're inside Yelp, it'll build with yelp-meteorite.
new: `make yelpy`
`make deb_bionic` - i saw the diff apply from `extra_requirements_yelp.txt` >> `requirements.txt`, which made the build install yelp-meteorite
I won't release this until next week
=> Install yelp-meteorite when building yelp env

tron/kubernetes.py
I incorrectly "fixed" some code when porting from Mesos -> Kubernetes
and introduced a bug
=> Make copy of k8s tasks while iterating to stop them

tests/core/actionrun_test.py, tests/core/recovery_test.py, tests/kubernetes_test.py, tron/core/actionrun.py, tron/core/recovery.py, tron/kubernetes.py
With https://github.com/Yelp/task_processing/pull/175 our KubernetesPodExecutor will support `reconcile(KubernetesTaskConfig)`.
When tron is starting up, it will attempt to [recover all jobs](https://github.com/Yelp/Tron/blob/master/tron/mcp.py#L141) [from saved state](https://github.com/Yelp/Tron/blob/master/tron/core/job_scheduler.py#L27-L45) and call [action_run.recover() for each still-running action_run](https://github.com/Yelp/Tron/blob/master/tron/core/recovery.py#L23-L34).
This implements KubernetesActionRun.recover to be handled during that startup process^, which in turn calls KubernetesCluster.recover, which will call KubernetesPodExecutor.reconcile().
The implementation is nearly identical to the mesos version and is tested in the same way.  The only exception is that because …
=> Implement reconciling & task recovery for Kubernetes

requirements.txt, tests/core/actionrun_test.py, tron/core/actionrun.py
We had left this method stubbed out until we implemented kill()
in task_processing, but now we can actually finish implemention here.
=> Actually kill k8s Pods on KubernetesActionRun::kill()

tron/kubernetes.py
We're missing these for parity with the logging done by our existing
Mesos tasks
=> Log k8s task config and hostname of agent

requirements.txt, tests/core/actionrun_test.py, tron/core/actionrun.py
in #829 we implemented recover() for KubernetesActionRuns and depended on job_collection.recover_state to eventually call this; however I missed handling KubernetesActionRuns when restoring an action run from state, so these jobs were recreated as SSHActionRuns erroneously.
In addition, #827 was also merged and added cap_add/cap_drop as required params to `create_task`, so these also need to be added when we recreate the task in `recover()`.
This fixes the issue and works well on our playground instance, and still-running pods are correctly updated to state `running` as expected.
=> TRON-1658: Fix issue restoring KubernetesActionRuns

tron/api/adapter.py
It turns out that we reset the start time for an ActionRun on any
retries, so let's use the start time from the first attempt and the end
time from the last attempt to figure out what timespan to ask for logs
from scribereader
=> Use start and end times from ActionRunAttempts

mypy.ini, requirements.txt, tests/config/config_parse_test.py, tests/core/actionrun_test.py, tests/kubernetes_test.py, tron/config/config_parse.py, tron/config/schema.py, tron/core/action.py, tron/core/actionrun.py, tron/kubernetes.py
We need node selector support for our "pool" concept and node
affinities will give us parity with the concept we had in Mesos of
"extra_constraints".
This additionally adds some error handling when things fail any
invariants for a KubernetesTaskConfig - previously, an
InvariantException meant that we would never realize that a
KubernetesTaskConfig was invalid and that the ActionRun would never
work.
=> Support node selectors/affinity for k8s tasks

tronweb/coffee/actionrun.coffee
This was missed when this view was initially created and is helpful for
users to determine how run times for a given action are changing over
time at a glance.
=> Show duration in ActionRun history table

tron/serialize/filehandler.py
https://docs.python.org/3/library/logging.handlers.html#streamhandler
mentions that any stream passed to a logging.StreamHandler should also
support a flush() method. Without this, we don't get any "meta" output
for k8s Tronjobs until the ActionRun has completed and the file has been
closed.
=> Add a flush() method to our FileHandleWrapper class

tests/utils/scribereader_test.py, tron/api/adapter.py, tron/utils/scribereader.py
It's possible that a tronjob in pnw-dev and norcal-devc could log to the
same stream (e.g., they have the same {namespace}.{job}.{action}
identifier and therefore will both log to
stream_paasta_app_output_{namespace}_{job}__{action}).
Currently, if this were to be the case and these jobs ran on the same
days with similar run numbers, we would mix the output from these two
runs when looking at the Tron UI for either of these.
Every task has a PAASTA_CLUSTER environment variable, so we can look at
the environment that we started a task with in order to filter the log
streams for these actions since these streams contain the cluster name
of where the logged message came from.
Therefore, we use this to ensure that we only display the correct log
messages to users instead of potentially mixing …
=> Filter per-instance Tronjob logs by cluster

requirements.txt, tests/core/actionrun_test.py, tests/kubernetes_test.py, tron/config/config_parse.py, tron/config/schema.py, tron/core/action.py, tron/core/actionrun.py, tron/kubernetes.py
We'll need this to set labels required by the PaaSTA Workload Contract
(which is needed to ensure that internal tooling will work as expected
with our Pods)
=> Support passing Pod labels to task_processing

requirements-dev.txt, requirements.txt, tron/kubernetes.py
It's possible to run Tron somewhere with incorrect config (e.g., when
doing local development or on a "real" Tron master that hasn't fully
run Puppet).
Without this change, this situation could result in Tronjobs that are
stuck in a "Starting" stage forever (at least, until you do something
like restart Tron and force a state reconciliation).
=> Handle exceptions when creating a kubernetes executor

requirements-dev.txt, requirements.txt, tron/kubernetes.py, yelp_package/extra_requirements_yelp.txt
We duplicate the ecosystems that we can point scribereader at in the
package and that list was missing corpdev
This causes a KeyError when trying to get the tailer host:port tuple for
tron in corpdev
=> Upgrade scribereader so that we can read logs in corpdev

requirements.txt, tests/kubernetes_test.py, tron/config/config_parse.py, tron/config/schema.py, tron/core/action.py, tron/core/actionrun.py, tron/kubernetes.py
We'll use this for Pod Identity - there's a webhook that will inject
a secret token + some environment variables if a Pod has a Service
Account set up.
paasta-tools will be in charge of creating the Service Account that
we'll use if it doesn't exist (as well as setting up the annotations on
that Service Account).
NOTE: tests will fail until https://github.com/Yelp/task_processing/pull/186 is merged/released, but I tested this locally with a manually built task_proc wheel (both automated tests and actually running a Pod)
=> Add Service Account support for k8s jobs

tron/command_context.py
Some users have jobs whose output depends on the output of the previous
run - for critical jobs, it's useful to explicitly declare this
dependency so that these jobs never run unless Tron knows that the
previous output is ready/complete (using successful completion as a
proxy for this)
For additional context: https://yelp.slack.com/archives/CA4K8PBLG/p1638402768180500
=> Allow users to use runid for triggers

tests/core/actionrun_test.py, tron/core/actionrun.py
I missed this create_task callsite in the initial PR - without this,
we'll fail to recover state when Tron restarts.
=> Pass service_account_name in create_task() during recovery

dev/logging.conf, tron/kubernetes.py, tron/logging.conf
This should cleanup any non-fatal exceptions that we see in Tron logs.
The logger changes silence yelp_clog complaining about being unable to setup signal handlers
and the kubernetes.py silences a somewhat rare traceback when we get task_proc events that somehow have no raw attribute (which happens when we recover jobs on a restart)
=> Silence yelp_clog.StreamTailer logs + k8s event guard

debian/tron.service
Tron somehow went down with exit 0 and therefore didn't come back up. I couldn't find any obvious reasons for how it could exit 0. The only way that Tron should be able is through a sigwait inside a `while True`, and in that case, it would only exit non-zero. At least this PR will make it always restart.
`systemd-analyze verify tron.service`
=> Always restart trond if it goes down

tron/api/adapter.py, tron/utils/scribereader.py
Callers can request a specific number of lines for logs - before this
change we were ignoring that (except for the k8s metadata logs) and
always returning all the data available.
=> Respect ActionRunAdapter max_lines param

tron/config/config_parse.py, tron/config/schema.py
For the upcoming work with Spark drivers on Kubernetes, we'll be
bubbling up the fact the `executor: spark` config from soaconfigs rather
than normalizing it to `kubernetes` (or `mesos` as we did for the
initial attempt at "paasta-native" spark drivers).
For now, this will do nothing - but it will allow us to start building
out stuff in paasta/soaconfigs without failing validation
=> Accept executor: spark

requirements.txt
https://github.com/Yelp/pysensu-yelp/pull/30 was released in
pysensu-yelp==0.4.4 and allows users to set the issuetype for a ticket
(so that sensu-created tickets aren't always of type `Bug` (the default))
=> Bump pysensu-yelp to pull in issuetype support

tox.ini, tron/core/actiongraph.py, tron/core/jobrun.py
Core ML would like to be able to use this log for dashboarding purposes,
but there's currently no trivial way to partition actions by type with
the information in the log (without doing some funky joins on other
data)
=> Tag state updates with executor (if available)

bin/tronctl, cluster_itests/docker-compose.yml, tests/commands/retry_test.py, tron/commands/retry.py, yelp_package/bionic/Dockerfile
This PR gives `tronctl retry` a new option, `--wait-for-deps` that, if set, will make `tronctl` wait for all upstream triggers and required actions to complete before attempting to retry a given action. An arg can be passed to the option specifying a timeout, including "infinity" (i.e. never timeout), for how long to wait before giving up.
By default, the behavior of not waiting before retrying is preserved. However, I've made it so that even with the default timeout of 0 (i.e. don't want), we check to make sure all dependencies are done, because the current behavior is to issue a retry, to which the server will respond with an OK, even if the retry will fail anyway because dependencies are not done.
`make test`
manual testing on an example cluster, using a job with an action that has …
=> Add arg to `tronctl retry` for waiting for dependencies

requirements.txt, tests/core/actionrun_test.py, tests/kubernetes_test.py, tron/config/config_parse.py, tron/config/schema.py, tron/core/action.py, tron/core/actionrun.py, tron/kubernetes.py
we need this for spark drivers in k8s to work - and without the field selector env vars we're not able to fully adhere to the paasta workload contract
=> Pass port/field selector envvars to task_proc

Makefile, package.json, tronweb2/package.json
Our internal build now runs inside a container whose `hostname` no longer matches `yelpcorp.com`.
This instead changes our makefile to set internal-only things based on `PAASTA_ENV`, and a separate change will force our internal build to set `PAASTA_ENV=YELP` when building. 
In addition to the internal build PIP problem, a dependency for one of our node eslint checks was updated to a version that was no longer compatible w/ node <12.0.  To minimize potential breakage on tronweb, I am just pinning to an older version of axe-core for now, and will ticket updating to node 12+ separately.
This got past `make test` on an internal build on k8s: https://jenkins-test.yelpcorp.com/blue/organizations/jenkins/test-jfong-tron/detail/test-jfong-tron/6/pipeline/ e.g. with `15:06:08  Now running on …
=> Fix internal build

requirements.txt, tron/kubernetes.py
https://jira.yelpcorp.com/browse/TRON-1743
set custom user agent for k8s client usage from tron/task_proc
Bumped up task-processing version used by Tron.
Pass tron version info to task-processing which will be used for setting the useragent as per the changes in [this PR](https://github.com/Yelp/task_processing/pull/195)
=> bumped up taskproc ver pass tron version to tskprc gsf

requirements.txt
see https://github.com/Yelp/task_processing/pull/198
version 0.9.0 is already available in our internal pypi. 
Manually tested on our tronplayground host and confirmed no breakage (although still working on reproducing a 401 specifically to confirm the fix).
Difference in versions is available at: https://github.com/Yelp/task_processing/compare/v0.6.0..v0.9.0
Notably there are more changes than just the fix that could have some impact on security contexts on pods, so I will be sure to verify in our test clusters before this rolls out to prod.
=> TRON-1777: bump taskproc to get kubeconfig reload fix

tron/bin/check_tron_jobs.py
This should help with skipping logging for specific superregion. I'm not really sure how to test this so will need to test before merging.
This is tested with the failed job compute-infra-test-service.test_failure:
With the new command:
`/opt/venvs/tron/bin/python /opt/venvs/tron/bin/check_tron_jobs.py --run-interval 600 -vvv --server xxxxx --job compute-infra-test-service.test_failure --skip-sensu-failure-logging`
https://yelp.slack.com/archives/CA57DEF19/p1665171337097219
without the new command:
`/opt/venvs/tron/bin/python /opt/venvs/tron/bin/check_tron_jobs.py --run-interval 600 -vvv --server xxxxxx --job compute-infra-test-service.test_failure`
https://yelp.slack.com/archives/CA57DEF19/p1665171444443389
=> TRON-1806 Adds new function in check_tron_jobs to skip failed logging queries for a specific superregion

.pre-commit-config.yaml, tests/kubernetes_test.py, tron/core/actionrun.py, tron/kubernetes.py
this is kinda wild: we're seeing that a kubelet will sometimes fail to start a container (usually due to what appear to be race conditions like those mentioned in https://github.com/kubernetes/kubernetes/issues/100047#issuecomment-797624208 and then decide that these Pods should be phase=Succeeded with an exit code of 0 - even though the container never actually started.
So far, we've noticed that when this happens, the `finished_at` and `reason` fields will be `None` - thus we'll check for at least one of these conditions to detect an abnormal exit and actually "fail" the affected action
=> Detect abnormal successful exits in k8s

tests/kubernetes_test.py, tron/kubernetes.py
The data we'd been dumping into our logging streams was using different key names than what task_proc was actually sending k8s: we were logging the python-ified names, but task_proc was sending tron the literal k8s payloads (i.e., keynames being camelCased).
We didn't notice this 'cause until the initial attempt at working around this weird k8s bug we weren't actually logging what tron was seeing and our test data in the unit tests was based on what we'd been seeing in our logging streams
=> Use correct dict casing for k8s metadata

bin/tronctl, tests/commands/client_test.py, tests/commands/retry_test.py, tron/commands/backfill.py, tron/commands/client.py, tron/commands/retry.py
This adds an option to our tron Client to add the current username to the useragent when connecting to the API.
This then adds attribution to any client calls through tronctl (though i also see an argument for just adding it to everything by default too, if we wanna go that route).
Manually ran a few tronview commands and confirmed user-agent remained the same in the logs, and confirmed tronctl commands added the user attribution
Tronview:
```
Dec  2 10:00:36 tronplayground1-uswest1cdevc tron.api.www.access b'"127.0.0.1" - - [02/Dec/2022:18:00:35 +0000] "GET /api/jobs/paasta-contract-monitor.long_job?include_action_runs=0&num_runs=10 HTTP/1.1" 200 5452 "-" "Tron Command/1.23.7 +http://github.com/Yelp/Tron"'
```
Tronctl:
```
Dec  1 18:46:04 tronplayground1-uswest1cdevc tron.api.www.access …
```
=> TRON-1723: Add user attribution into user agent when invoking tronctl commands

debian/control, debian/tron.service
This PR adds a ExecStopPost to the systemd unit file to log tron exit status
=> Adding ExecStopPost to systemd unit file to log tron exit status

package.json, requirements-docs.txt, requirements-minimal.txt, requirements.txt, tron/kubernetes.py, tron/trondaemon.py, tronweb2/package.json
This PR upgrades some requirements to help us as we are seeing events being lost by Tron in pnw-devc on Python 3.8
- Upgrades Twisted to the latest version to support python 3.8
- Upgrades axe-core as previous version was incompatible
- adds lru_cache to logging to stop kubernetes from [locking on get loggers](https://github.com/kubernetes-client/python/issues/1867)
- Upgrades all dependencies recommended by dependabot to address security severities and further future proof.
=> Upgrades requirements and adds caching on get loggers

tron/ssh.py
We're seeing these warnings happen when running tronctl after upgrading twisted. This is due to twisted upstream library and is safe to ignore. Ideally we can remove this workaround once it's removed in twisted.
```
❯ tronctl -h
/opt/venvs/tron/lib/python3.8/site-packages/twisted/conch/ssh/transport.py:97: CryptographyDeprecationWarning: Blowfish has been deprecated
b”blowfish-cbc”: (algorithms.Blowfish, 16, modes.CBC),
/opt/venvs/tron/lib/python3.8/site-packages/twisted/conch/ssh/transport.py:101: CryptographyDeprecationWarning: CAST5 has been deprecated
b”cast128-cbc”: (algorithms.CAST5, 16, modes.CBC),
/opt/venvs/tron/lib/python3.8/site-packages/twisted/conch/ssh/transport.py:106: CryptographyDeprecationWarning: Blowfish has been deprecated
b”blowfish-ctr”: (algorithms.Blowfish, 16, …
```
=> Ignores CryptographyDeprecationWarning

tests/utils/timeutils_test.py, tron/utils/timeutils.py
```
>>> from tron.utils.timeutils import DateArithmetic
>>> da = DateArithmetic()
>>> da.parse('shortdate - 1')
'2023-03-08'
>>> da.parse('shortdate-1')
'2023-03-08'
>>> da.parse('shortdate - 2')
'2023-03-07'
```
=> TRON-1859: Updates date arithmetic to handle whitespace

tests/kubernetes_test.py, tron/kubernetes.py
This changes a few things about our event handling:
1. This updates the "missing state" check to match only if the actual "state" data was missing from the pod event, rather than also matching when "state" existed but "terminated" state data was missing.  Because we safely attempt to extract the "terminated" state with a valid empty default value if it's not found, this should not impact any later logic. 
If a terminal event was sent, but the main container 'state' did not include 'terminated', this PR adds a new condition to check for this and assumes we encounted a node scaledown (likely the only way the pod was terminal but container did not fully terminate), and so we return EXIT_KUBERNETES_NODE_SCALEDOWN.
Also added a test for this condition
2. Our default exit code was `1`, which …
=> Handle abnormal events & pod evictions before containercreated better

bin/tronctl, tron/commands/backfill.py
Problem 
-----
The Kubernetes control plane can be overwhelmed if a high number of concurrent backfills are executed. We currently set a relatively high default of `10` and enforce no upper limit at all.
Solution
-----
* Reduce the default `--max-parallel` from `10` to `3` to reduce the baseline pressure of Tron backfill jobs.
* Introduce and enforce a hard limit of `10` concurrent backfills per tronctl invocation
In a future PR, we might want to track the total count of running backfills per user in Zookeeper but this change should already safeguard against overwhelming Tron with backfills in the meantime.
Signed-off-by: Max Falk <gfalk@yelp.com>
=> COMPINFRA-2565: enforce an upper limit on backfill concurrency

tron/bin/check_tron_jobs.py
Copy pasting is hard. [eg](https://yelp.slack.com/archives/C03JPJ3GJUV/p1685961039895269). I'd like to just click on the link in slack.
=> Link tronweb_url 

tron/utils/scribereader.py
The current shell pipeline prints out every line surrounded by quotes, which is a bit annoying when sharing logs (or snippets of logs) with other people since you either need to manually clean up the logs to strip the quotes or live with the shame of sending someone ugly-looking text :p
=> Print raw output in scribereader fallback command

debian/rules, requirements.txt
This is to handle the recent breakage caused by us not always using pre-built wheels for our dependencies.
Switching off of pip-custom-platform would be a better fix but, just like in PaaSTA, this is likely to be quite a bit of work so for now we can simply upgrade our PyYAML.
=> Update to PyYAML==6.0.1

Makefile, debian/rules, tox.ini, yelp_package/bionic/Dockerfile
This is controlled via the `/etc/pip.conf` file which is managed by Puppet on yelpcorp hosts.
This should also get rid of the need to use pip-custom-platform.
=> Don't hard-code yelpcorp PyPI registry

tron/config/schema.py
This PR fixes the schema assumption that configsecretVolume's "items" field is an array. I did not find the source of the array to tuple transformation, but this is the only place in the code that assume it's a writable array, so this also resolve the problem.
This [test job was used](https://github.yelpcorp.com/sysgit/yelpsoa-configs/pull/33389/files) with a locally modified version of tron in infrastage.
BEFORE change: https://fluffy.yelpcorp.com/i/7h1Tdwvblkf4KKKxz74V4T83XSbDxfsL.html
run successfully on infrastage: https://fluffy.yelpcorp.com/i/RWBcgXWqVfcsrFVXf9rtwfN6B9N7RpT4.html
retries successfully on infrastage: https://fluffy.yelpcorp.com/i/0d9hRM3hQ3KWv0nSDcHtTKGDLK7phXpt.html
The (currently) failing itest is also present for working commits in master. I don't know what this is …
=> Fix item assignment issue with ConfigSecretVolume

cluster_itests/docker-compose.yml, yelp_package/itest_dockerfiles/tronmaster/Dockerfile
Something appears to have changed with either GHA or the docker-compose version we're pulling in and the existing symlink setup looks to be confusing docker-compose.
We can probably cleanup (or delete) these cluster itests since they're all mesos-related, but that's a bigger change for another day :)
=> Un-symlink itest dockerfiles

tron/core/actionrun.py
It's entirely possible that creating a task_processing task (and/or submitting one) can result in an exception. At the moment, this results in the affected ActionRun getting stuck in the Starting state - but this is a lie and means that the normal monitoring/alerting on failed runs does not kick in.
=> Catch all exceptions in k8s submit_command()

docs/jobs.rst
This is not actually required - this is likely outdated docs from the pre-Mesos/K8s days.
=> Remove incorrect action_runner requirement from max_runtime docs

tron/bin/check_tron_jobs.py
Reverts Yelp/Tron#911 as this did not actually result in a link in Slack
=> Revert "Link tronweb_url "

.readthedocs.yaml
Similar to https://github.com/Yelp/paasta/pull/3745 , we need to add the new RTD v2 config file.  
They thankfully still support py3.6 on focal, and the build seems to work as expected on a personal fork + rtd project:
https://test-jfong-tron.readthedocs.io/en/latest/man_tronctl.html
https://readthedocs.org/projects/test-jfong-tron/builds/22836317/
Latest passing build of our public docs seems to have run nearly the exact same set of commands (although curiously ran on py3.7 instead of 3.6! I think it's fine to stick w/ 36 to match the service repo + bump to 3.8 when we do everything tho):
https://readthedocs.org/projects/tron/builds/19664551/
=> TRON-2035: Fix public docs w/ new RTDv2 config

yelp_package/extra_requirements_yelp.txt
We had bumped this a couple major versions since we were also bumping scribereader - but we reverted the scribereader bump before merging the jammy/py38 branch and forgot to also revert the yelp-clog bump :)
=> Downpin yelp-clog

tests/utils/scribereader_test.py
This is what I get for trusting GHA rather than also running the tests internally :)
These mocks are no longer required and are actually causing test failures internally.
=> Remove unnecessary mocks

tests/eventbus_test.py, tron/eventbus.py
We've never restored from these "backups", and as long as we ensure that the current file points to a fully written file, it's fine to only keep at most 2 files around: the actual current file and a temporary "new" file.
To ensure that we're not pointing at a half-written file, we continue using the age-old pattern for atomic file updates: write to another file and swap a symlink once the write is complete
=> Stop keeping old copies of eventbus files

tron/utils/scribereader.py
To filter stdout/stderr logs in the scribereader command, which users are adviced to run.
=> change to
```
scribereader -e pnw stream_paasta_app_output_spark_spark_driver_test_redshift__test_redshift --min-date 2024-02-23 | jq --raw-output 'select(.tron_run_number==0 and .component=="stdout") | .message'
```
=> Specify stdout or stderr in the scribereader command

requirements-minimal.txt, requirements.txt, tests/api/resource_test.py, tron/api/resource.py, tron/kubernetes.py, tron/prom_metrics.py
This PR adds prometheus endpoint at the path /api/prom-metrics and adds gauges for some of the metrics to test it out.
=> Adding prometheus endpoint in tron - TRON-2124

tronweb/coffee/actionrun.coffee, tronweb/coffee/models.coffee
Escape HTML in command, stdout, and stderr
[Before](https://fluffy.yelpcorp.com/i/sZ2x8dNzwmpp5DbZxv1fHfSf6qGDhDzf.png) and [after](https://fluffy.yelpcorp.com/i/MHgSkHnPs614l2djCr7T7ZCFJ1f02FxB.png).
=> Use Underscores HTML escaped interpolation in template for log and command outputs

bin/trond
As the comment says: let's see if adding a top-level handler (that then re-raises) and catching BaseException will give us more info as to what's sometimes causing Tron to exit.
I've also added the usual base exception (Exception) just to be extra-safe
(h/t to krall for the idea)
=> Add a top-level exception handler

tests/bin/check_tron_jobs_test.py, tron/bin/check_tron_jobs.py
We can sometimes get stuck in state `starting` if we somehow miss events coming in from k8s (or a pod somehow itself get stuck before it starts running).
This should now consider these situations as `stuck` jobs and actions alongside those that are actually running too long or waiting on a trigger, and adds some tests to verify. (These tests were confirmed to fail w/o the changes to include 'starting' jobs/actions).
=> TRON-1850: Include starting pods in check for stuck jobs

mypy.ini, requirements-dev-minimal.txt, requirements-dev.txt, requirements.txt, tests/utils/scribereader_test.py, tron/commands/backfill.py, tron/commands/display.py, tron/core/actionrun.py, tron/utils/scribereader.py, yelp_package/extra_requirements_yelp.txt
Enabling `S3LogsReader` from yelp_clog as an alternative method for reading tron Paasta logs.
=> Adding yelp_clog S3LogsReader

requirements.txt, tron/kubernetes.py
We've seen that task_proc/k8s will sometimes not correctly send events for pods that we try to kill ourselves (either because the pods are already gone or because the event is somehow missing data), so this task_proc version will send synthetic events when we call kill() to ensure that tron is in the correct state :)
=> Update task_proc to better handle killing tasks

tests/config/config_parse_test.py, tests/mcp_test.py, tron/config/config_parse.py, tron/config/schema.py, tron/mcp.py
This PR deletes the "mesos_options" flag from the MCP, next will delete the Mesos code from files that restore Tron's state
=> Deleting Mesos code from the Master Control Program - TRON-2182

tests/serialize/runstate/statemanager_test.py, tron/serialize/runstate/__init__.py, tron/serialize/runstate/statemanager.py, tron/trondaemon.py
This PR deletes code from the statemanager in Tron which save state for mesos clusters, next will tackle actionrun and recovery
=> Delete Mesos code from statemanager - TRON-2183

.github/workflows/ci.yml, .readthedocs.yaml
Ever since we upgraded Tron to python 3.8 on Tron version 1.28.0 the doc builds have been failing. This should fix the docs
=> update to jammy and fix docs build on 3.8

dev/logging.conf, tron/logging.conf
These are useless since this code is never hit (or is being deleted)
=> Delete Mesos logging config

README.md
This fixes the build status icons in the README and removes references to Mesos
=> TRON-2185: cleanup mesos docs in Tron

tests/serialize/runstate/dynamodb_state_store_test.py, tron/serialize/runstate/dynamodb_state_store.py, tron/serialize/runstate/statemanager.py
This PR adds a try/except block to where we call result() to catch any exceptions that might happen in the threads span by ThreadPoolExecutor.
I tested if with this change we now catch an exception thrown by "_restore_runs_for_job" and exit the trond process. This works so I added it to the BatchGetItem call as well where we call result()
=> Handling exceptions thrown from threads span by ThreadPoolExecutor - TRON-2202

tests/utils/scribereader_test.py, tron/utils/scribereader.py, yelp_package/extra_requirements_yelp.txt
Updating `yelp_clog` that comes with two changes in S3LogsReader:
- usage of `superregion` as a parameter to determine the prefix from where to fetch logs in S3
- usage of UTC dates as a standard timezone for logs stored in S3
=> Use S3LogsReader with superregion and UTC timezone

bin/tronctl, tron/commands/cmd_utils.py
As we learned in a recent incident, if there are any issues with the DynamoDB data, it's possible for us to end up re-enabling jobs. We've previously warned folks in the past (in Slack/IRC/etc) that to permanently disable jobs it's recommended that they do so in soaconfigs, but this is easy to forget and not everyone will reach out before disabling a job that they don't expect to re-enable any time soon.
=> Add warnings about tronctl disable not being permanent

tron/config/config_parse.py, tron/config/schema.py
In DAR-2328, we learned that if Tron reads from a DynamoDB that has data that references deleted classes (or attributes), we'll run into deserialization issues (i.e., pickle will fail to resolve the serialized class in the first place or fail to reconstruct the serialized class)
=> Add warnings to files that deal with serialized models

tests/config/config_parse_test.py, tron/config/config_parse.py, tron/core/action.py
Follow up to https://github.com/Yelp/Tron/pull/975, where it looks like I missed a couple of places in the call stack to get the action configuration passed downstream.
Honestly, the amount of yak-shaving required to get a new setting going is concerning.
=> pass around projected SA configs properly

tron/serialize/runstate/dynamodb_state_store.py
This fixes an issue where we were appending a list of lists to a list of key dicts, which resulted in the following error since boto's batch_get_items expects only a list of key dicts:
```
Jun 17 17:07:22 tron3-uswest2bdevc tron[3313674]: ERROR pid=3313674 tid=140237946082880 tron.serialize.runstate.dynamodb_state_store _get_items:102 Encountered issues retrieving data from DynamoDB
File "/opt/venvs/tron/lib/python3.8/site-packages/tron/serialize/runstate/dynamodb_state_store.py", line 91, in _get_items
items.extend(resp.result()["Responses"][self.name])
File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
return self.__get_result()
File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
raise …
```
=> Fix UnprocessedKeys bug when restoring from dynamodb

tron/config/config_parse.py, tron/config/schema.py
A revert is essentially a delete, but I don't think many of us would treat one the same as an explicit delete given that generally reverting code is a safe operation :)
=> Add clarification around reverting changes that touch DynamoDB data

tron/utils/scribereader.py, yelp_package/extra_requirements_yelp.txt
yelp_clog 7.1.3 also drops `ecosystem` parameter from `S3LogsReader` interface
=> Update yelp_clog and use datetime range for S3 logs

tests/utils/scribereader_test.py
Fixing scribereader tests for previous change: https://github.com/Yelp/Tron/pull/979
=> Fix failing scribereader tests

tests/tools/sync_tron_state_from_k8s_test.py, tools/sync_tron_state_from_k8s.py
This adds a pretty simple script that will:
1. search for any completed pods in the tron namespace given a KUBECONFIG
2. attempt to match those pods with any existing action runs that are in a state that can be updated
3. update the state w/ `tronctl` if the pod & tron's states do not match.
Tron will only allow us to transition from a few known states, so this script only allows using `tronctl fail` or `tronctl succeed`  if the tron action run was either lost/unknown or 'stuck' at `running` or `starting`. 
Right now, I allow passing both a tron-url + tronctl-wrapper so that this could be run from outside the tron server itself, but defaults assume we'll be running on a local tron server. 
Still adding some tests but thought I should get feedback now in case I need to shift gears. …
=> TRON-2210: Add a tool that can sync from pod state to tron w/ tronctl

bin/tronctl
I'm not sure I was thinking here since this ended up unconditionally printing the disable warning - but we can chalk this up to an intentional PR campaign to warn folks and only show the warnings on tronctl disable from now on :p
=> Only show disable warning on tronctl disable

requirements-minimal.txt, requirements.txt, tests/config/config_parse_test.py, tron/config/config_parse.py, tron/config/schema.py, tron/kubernetes.py
Requires https://github.com/Yelp/task_processing/pull/213 & new version of taskproc to be released.
This adds the support to tron's MASTER config's `k8s_options` to allow the new `old_kubeconfig_paths` option and passes it along to task_processing's kubernetes_pod_executor.
=> TRON-2195: Support watcher_kubeconfig_paths

tools/sync_tron_state_from_k8s.py
If an action supports retries then we migrate to a new cluster while a job is ongoing, some attempts for this action could live on the old cluster and others on the new. 
In order to catch this situation, sync_tron_from_k8s needs to be able to inspect pods in both old & new clusters to determine the correct tron state. 
This simply allows specifying multiple kubeconfigs and gathering _all_ pods from all clusters in order to compare against potentially-updateable actions.
This has been verified to work with multiple kubeconfigs for both eks and non-eks infrastage, and I've verified the metadata.creationTimestamps appear to be in UTC so will be consistent across clusters so we are comparing timestamps appropriately. 
(Note that this means running from the devbox is not quite as convenient …
=> Support multiple clusters in sync_tron_from_k8s

.gitignore, requirements-dev-minimal.txt, requirements-dev.txt, tests/config/config_parse_test.py, tests/kubernetes_test.py, tron/config/config_parse.py, tron/config/schema.py, tron/core/actionrun.py, tron/kubernetes.py, tron/utils/exitcode.py
This PR addresses [TRON-2208](http://y/TRON-2208) by adding a toggle in the Tron configuration to disable automatic retries for Kubernetes jobs that are marked as "LOST". This is particularly useful for non-idempotent jobs where retries can be dangerous.
- **`tron/config/config_parse.py`**: Added `non_retryable_exit_codes` to the Kubernetes configuration schema.
- **`tron/config/schema.py`**: Updated the schema to include `non_retryable_exit_codes`.
- **`tron/core/actionrun.py`**: 
- Modified the `_exit_unsuccessful` method to check for `non_retryable_exit_codes` and skip retries if the exit code is in this list.
- Refactored `non_retryable_exit_codes` to use a list instead of a tuple.
- **`tron/kubernetes.py`**: 
- Updated the `handle_event` method to set the exit code to …
=> TRON-2208: Add toggle in tron config to disable retries on LOST k8s jobs

tron/config/config_parse.py, tron/config/config_utils.py
This pull request fixes a bug in the Kubernetes configuration where a negative value was not properly checked for non-retryable exit codes.
=> Fix negative value check for non-retryable exit codes in Kubernetes configuration

tron/api/controller.py, tron/api/resource.py, tron/config/manager.py
Right now we make at most 2N calls to the Tron API during config deployments: N to get the current configs and at most N if all services have changes.
To start, I'd like to reduce this to N by allowing GET /api/config to return all the configs so that the only requests needed are POSTs for changed configs.
Depending on how this goes, we can look into batching up the POSTs so that we can also do that in a single request.
In terms of speed, it looks like loading all the configs from pnw-prod (on my devbox) with this new behavior takes ~3s - which isn't great, but there's a decent bit of file IO going on here :(
=> Attempt to batch config loading for deployments

tests/config/config_parse_test.py, tests/core/actionrun_test.py, tests/kubernetes_test.py, tron/kubernetes.py
Looks like we missed one place where we need to pass along the k8s_options from MASTER configs, when we instantiate our `KubernetesCluster`s from `KubernetesClusterRepository`.
Applying this change to a local instance and infrastage now do what we expect and do not retry failed actions if their exit codes are in non_retryable_exit_codes, plus logs what we expect:
```
2024-09-25 17:00:22,786 tron.core.actionrun INFO ActionRun: MASTER.testjob0.14.zeroth skipping auto-retries, received non-retryable exit code (72).
2024-09-25 17:00:22,786 tron.core.actionrun INFO ActionRun: MASTER.testjob0.14.zeroth completed with fail, transitioned to running, exit status: 72
2024-09-25 17:00:22,786 tron.utils.state DEBUG transitioning from running to failed
2024-09-25 17:00:22,786 tron.utils.observer DEBUG …
```
=> TRON-2277: Pass along non_retryable_exit_codes to KubernetesCluster objects

tron/utils/scribereader.py
Thankfully, this was a pretty easy change - we really only needed to parametrize the command name being used and the location selector is now a lot simpler as it'll always be the superregion
=> Use vector-reader cli if new logging pipeline is enabled

tests/core/actionrun_test.py, tron/core/actionrun.py
This keeps things as UNKNOWN if we happen to match a non_retryable_exit_code rather than straight to FAILED, since we are primarily using this feature to capture things which have gone LOST on kubernetes and as such, we can then use our sync_tron_state_from_k8s script to update the action state based on pod state, which would not be possible if we already marked it as FAIL. 
This has been tested on infrastage and the [test run](http://tron-infrastage.yelpcorp.com:8089/web/#job/paasta-contract-monitor.test_no_retries/12/run) that exited with a non_retryable_exit_code successfully got marked as `unknown` and did not attempt any retries, plus the sync_tron_state_from_k8s script reported it would be able to correct the state:
```
DEBUG:sync_tron_from_k8s:paasta-contract-monitor.test_no_retries …
```
=> TRON-2208: Update non_retryable_exit_code behavior to treat as UNKNOWN

tests/utils/scribereader_test.py, tron/utils/scribereader.py
This PR introduces a new function, get_log_namespace, which retrieves the log namespace from yelpsoa-configs. The function is used in the PaaSTALogs class in scribereader.py to set the namespace for logging. 
The PR also includes unit tests for the get_log_namespace function.
Closes TRON-2275
........tested manually and seems to work fine
=> Fixing Tron logs for jobs using other services images

tron/core/actionrun.py, tron/serialize/runstate/dynamodb_state_store.py
I think total_seconds is the easiest to convert back to timedelta later. I added some logging that might be noisier than we want longterm, but should make debugging these a lot easier.
Recreated the errors in infrastage and this does appear to resolve things.
Sidenote, I'm happy to leave this unmerged while doing more testing in dev/stage to maybe minimize the number of patch releases.
=> Use total_seconds for timedeltas. Log job and jobrun names/runnums on serialization

CODEOWNERS
To start, we can add ourselves as CODEOWNERS for the entire repo since (at least for the time being), we probably want to be aware of/sign-off any changes to Tron
=> Add default CODEOWNERS

tests/config/config_parse_test.py, tests/serialize/runstate/statemanager_test.py, tron/config/config_parse.py, tron/config/schema.py, tron/mcp.py, tron/serialize/runstate/dynamodb_state_store.py, tron/serialize/runstate/shelvestore.py, tron/serialize/runstate/statemanager.py
This adds the read_json to be a config in master.yaml instead of srv-configs. It makes it easier to set this option per Tron Master.
Tested this by setting read_json in master.yaml and checked if the json deserialization was enabled or not
=> Add read_json to be a part of master.yaml config

tron/serialize/runstate/dynamodb_state_store.py
As we have seen in norcal-stagef not having this try/except caused the jobs to reset when we didn't have a json_val written for them in the db. We should capture this and handle it.
=> Capturing exception when json_val doesnt exist

requirements.txt
Just like Yelp/paasta#3972 and Yelp/paasta#3973, we need to ensure that there are no duplicates between cap_add and cap_drop - otherwise, the cap_drop entry will "win" and the duplicate capability will not be added.
=> Bump task_processing to v1.3.1 for capability fix

.github/workflows/ci.yml
See https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> Switch to v4 of the artifact actions

tests/serialize/runstate/dynamodb_state_store_test.py, tron/serialize/runstate/dynamodb_state_store.py
We need to update the logic for deleting items to account for a difference in partitions between pickles and json
=> Update delete_item logic to handle json partitions

tron/serialize/runstate/dynamodb_state_store.py
We need to do this now that json is our default
=> Pass json_val back to the save queue on failure

tronweb/coffee/views.coffee
Working my way through some UI bugs that I've stumbled upon. This was pretty tricky to solve because we use an ancient version of bootstrap. 
>  We choose to fix Tron. We choose to fix Tron... We choose to fix Tron in this decade and do the other things, not because they are easy, but because they are hard! 
> \- John F. Kennedy
- [Before](https://fluffy.yelpcorp.com/i/RH33zkzJmSZrrqXn8rgQDmGg6nm8DzT5.gif)
- [After](https://fluffy.yelpcorp.com/i/QB5pnhZzHCqNdK4598HLznJ9RNJ1pFQT.gif)
=> Disable the tooltip animation that is causing a strange problem where you can't get a tooltip when entering from the top of an object

tron/serialize/runstate/dynamodb_state_store.py
We need to check for the existence of the pickle partition. We also need to be adding the JSON partitions together instead of reassigning!
=> Add check for empty val. Merge json correctly

tron/core/jobrun.py
We recently encountered an issue where the `run_time` for JobRun instances was consistently offset by 7 minutes *earlier* than the expected time. This was causing scheduled Jobs to execute earlier than intended, leading to incorrect Job executions. 
This issue looks to related to our use of `run_time.replace(tzinfo=...)` which incorrectly handles timezone writing. This misuse resulted in the run_time being assigned a tzinfo with an unexpected offset, such as `<DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>`, which has an offset of -7 minutes from the expected timezone offset.
Note: I do think adding tests would be ideal, but I haven't gotten that far.
=> Use localize instead of replace when writing tz info

tron/core/action.py, tron/core/actionrun.py, tron/serialize/runstate/dynamodb_state_store.py
In this PR, we add the .get to some keys that we have seen error out when running the migration script in stage and that's because these jobs were too old and they didnt have some of these keys specified. If a key errors out, then there is no json val written for that action run. Thus, this PR sets a default value for those keys. It also adds a try/except to catch the scenario where a json_val doesnt exist for a key, otherwise I think it would fail silently and reset jobs to 0.
Note: I didn't change all keys to use .get instead, I wanted to change whatever was necessary as I think some keys should still error out on missing key if they are not optional? thoughts on this.
=> Add default behaviour for jobs that dont have some keys and handle the non-existent of some json_vals

tron/core/jobrun.py
This handles the case where a datetime object is timezone aware
- Installed the debian package on infrastage and observed the jobs schedule. They are scheduled correctly on their expected time.
- Inspected the code manually for timezone values to see if they make sense
=> Handling timezone aware jobs

tron/config/config_parse.py, tron/config/manager.py
There's enough files (and enough YAML in these files) that the IO/YAML parsing takes a significant amount of time.
While it's nice to always load from the source-of-truth (i.e., the files on-disk) - it's not worth paying the performance penalty (especially at the scale we're seeing internally) for a negligible benefit.
Locally (with a large test config), this results in a ~5x improvement in timings. More concretely, my test configs were taking ~30ish seconds *without* this diff and ~6ish seconds *with* this diff.
=> Try to load config_name_mapping from disk just once

tests/api/auth_test.py, tron/api/auth.py, tron/api/resource.py, tron/commands/client.py, yelp_package/extra_requirements_yelp.txt
This is a carbon copy of https://github.com/Yelp/paasta/pull/3985, as eventually we'll want to have authentication on these APIs too.
=> auth support for Tron APIs

tron/api/resource.py
In https://github.com/Yelp/Tron/pull/1005 I misinterpreted the way the Twisted web framework works, as I thought that by overriding the `render` method in the root API resource that would get called also for all the child page declared by that class.
That is not the case, so this creates a new base class which I'm explicitly setting as the base for all relevant API resources (I left out "status" and "metrics" since I had no intention of having them authenticated anyways).
=> fix auth middleware integration

requirements.txt
This includes https://github.com/Yelp/task_processing/pull/225, which should add some backoff to watch restarts to avoid slamming the apiserver
=> Update task_processing to 1.3.4 for watch backoff

tests/serialize/runstate/dynamodb_state_store_test.py, tron/serialize/runstate/dynamodb_state_store.py
There is no world where we can write 100 items of our chunk size without hitting the cap.
=> Reduce transact size to avoid cap

tron/commands/client.py, yelp_package/extra_requirements_yelp.txt
The new version adds an option to use an authentication flow with refresh tokens, which will allow `tronctl` commands to be run unattended for over the set duration of an identity token (which is fixed to 1 hour). Refresh tokens are valid for 90 days, which should be more than enough for all use cases.
=> use refreshable tokens for api auth

requirements.txt, yelp_package/extra_requirements_yelp.txt
Hadn't noticed, but changes from https://github.com/Yelp/Tron/pull/1048 introduced some annoying warnings for the CLI, and this couple of tweaks should fix them.
```
/opt/venvs/tron/lib/python3.8/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (5.2.0)/charset_normalizer (2.0.12) doesn't match a supported version!
warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named 'service_identity''.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client …
```
=> fix some annoying warnings

tron/api/resource.py
When implementing this I didn't notice that the API client actually expects an error field in the response body.
```
File "/usr/bin/tronctl", line 475, in <module>
main()
File "/usr/bin/tronctl", line 463, in main
for ret in cmd(args):
File "/usr/bin/tronctl", line 339, in control_objects
yield request(urljoin(args.server, tron_id.url), data)
File "/usr/bin/tronctl", line 233, in request
response = client.request(url, data=data, headers=headers, method=method, user_attribution=True)
File "/opt/venvs/tron/lib/python3.8/site-packages/tron/commands/client.py", line 92, in request
return build_http_error_response(e)
File "/opt/venvs/tron/lib/python3.8/site-packages/tron/commands/client.py", line 74, in build_http_error_response
content = content["error"] …
```
=> return auth error that clients can parse

tests/commands/backfill_test.py, tron/commands/backfill.py
The `backfill` command makes multiple API calls in async tasks, which causes users to be prompted for authz in concurrent threads, which of course it's a problem.
This should ensure that authentication is performed before the tasks are launched, so that the user can auth once, and then the tasks will be able to rely on the cached token values.
=> cache auth tokens before starting backfill jobs

tron/commands/authentication.py, tron/commands/backfill.py, yelp_package/extra_requirements_yelp.txt
Tokens cached on disk are currently a problem if the user launches a long backfill job less than one hour after running another tronctl command. This ensures can in case of backfills the cached token is ignored, and a fresh long-lasting refresh token is stored into memory, allowing the backfill command to correctly function for multiple hours.
NOTE: do not merge, the new version of `okta-auth` is not released yet internally.
=> ignore cached okta token in backfills

tron/kubernetes.py, tron/utils/exitcode.py
Tron currently thinks any pods evicted for disk reasons are spot terminated, which confuses folks who don't know what to look for. The new error -13 (spooky 🎺💀) will catch disk evictions.
- Updated the current logic to look for an eviction message
- Fixed some typos
Tested in infrastage with a job that gets evicted and it works. I was also planning to include a hack to get this to the UI but I think I'll leave that to another time because it's kind of gross.
=> Add disk eviction error code and check logic

bin/tronctl
This takes a trigger id (like `discard`), not an action id.
=> Fix inaccurate help text for tronctl publish

mypy.ini, tron/api/adapter.py
For once, a small mypy PR :p
There was just a single untyped decorator and I went ahead and wrote some inline comments 'cause I don't think I'll remember how to read this after this gets merged :deepfried-loljpg:
depends on https://github.com/Yelp/Tron/pull/1060 and https://github.com/Yelp/Tron/pull/1061
=> Enable disallow_untyped_decorators mypy option

debian/tron.service
Right now, our version of zk-flock will almost immediately (after a 1s delay) send a SIGKILL to the trond process during a restart, which prevents us from hitting all of our proper shutdown/cleanup code. 
With an [updated version](https://github.yelpcorp.com/packages/zk-flock/pull/25) of zk-flock, we can pass along a `--kill-timeout|-k` param to delay that SIGKILL, giving trond enough time to do what it needs to do. 
One other change required is that right now, we use the `KillMode` default of `control-group`: https://www.freedesktop.org/software/systemd/man/latest/systemd.kill.html which will kill all processes in the tree, including trond
Changing this to `KillMode=process` will ensure the SIGTERM is only sent to the parent process (zk-flock), which should then allow the signal to …
=> TRON-2340: Update tron unit file to ensure proper sigterm handling
