Yelp/Tron

contrib/find_forgotten_procs.py

Sometimes Tron loses state and spins up new processes, even though the previous processes are still there and running.
I've been using this script to find those forgotten processes.

Introduce find_forgotten_procs.py

---

contrib/find_forgotten_procs.py

* Move the `kill` call closer to discovery
* Make the output machine parseable
* Fix some niteries

More bells and whistles on find_forgotten_procs.py

---

contrib/find_forgotten_procs.py

Remove non-JSON output

---

.gitignore
.travis.yml
Makefile
setup.py
tests/commands/client_test.py
tests/config/config_parse_test.py
tox.ini
tron/commands/client.py

Primary: @asottile ?
I removed testify globally, and this is one of the few straggling things that doesn't use virtualenv.
This is my attempt to make it.. work?

Use tox for running tests

---

tron/serialize/runstate/yamlstore.py

Issues 306 & 326 

---

tests/serialize/runstate/shelvestore_test.py
tests/utils/tool_utils_test.py
tron/trondaemon.py

fixes  #305 
switch to using epoll reactor rather than poll on linux; use select
reactor everwhere else (should work on darwin)
fix broken tests in shelvestore_test

multi platform reactor; fix tests

---

docs/jobs.rst
tests/config/config_parse_test.py
tests/core/job_test.py
tron/config/config_parse.py
tron/config/schema.py
tron/core/job.py

Starting off with just a free-form dictionary, not adding strict validation yet.

Added monitoring dictionary for job configs

---

bin/check_tron_jobs
debian/tron.links
setup.py

This command loops over jobs and looks at their last run status.
Eventually it will send alerts to teams?
Till then I'll dogfood it.

Added prototype check_tron_jobs command

---

bin/check_tron_jobs
setup.py
tron/api/adapter.py

It is a little messy, but I think OK for "beta" and subject to change.
At least it "works" and we can actually start dogfodding this.
I hope oncall people will appreciate all the output. Here is an example:
https://pb.yelpcorp.com/309859
There are certainly lots to improve, but I think this is a good starting point.

Make check_tron_jobs actually send alerts with lots of context

---

bin/check_tron_jobs
bin/check_tron_jobs.py
debian/tron.links
tests/bin/check_tron_jobs_test.py
tron/commands/cmd_utils.py

Also starting to get this into shape with a test.
Also learning testify :(

Added dry-run and filtering on check_tron_jobs

---

docs/jobs.rst
example-cluster/logging.conf
example-cluster/start.sh
example-cluster/sync-from-yelp-prod.sh
example-cluster/tronfig/MASTER.yaml
setup.py
tests/config/config_parse_test.py
tests/core/job_test.py
tests/core/jobrun_test.py
tests/scheduler_test.py
tests/testingutils.py
tron/config/config_parse.py
tron/config/schema.py
tron/core/job.py
tron/core/jobrun.py
tron/scheduler.py
tron/utils/timeutils.py

US DST is coming up quickly on March 10.
It is embarrassing to me how many DST bugs we have every year because of tron. I would like to help eliminate some of them by allowing users to opt out on a per-job basis.
Internal ticket is TRON-117

Allow jobs to override the default timezone

---

tron/trondaemon.py

A more clear message here would have saved me some debugging time today

Make tron pidfile error message more clear

---

bin/check_tron_jobs.py
tests/bin/check_tron_jobs_test.py

now when job failed, it gets the failed action.
https://fluffy.yelpcorp.com/i/c2qZH46M9RDKPHGrnqQRS1CGNjHnrmt6.html
also add unit test for get_relevant_run and get_relevant_action

fix get relevant action bug and add unit tests

---

bin/check_tron_jobs.py
setup.py
tests/bin/check_tron_jobs_test.py

use pysensu 0.3.5
catch exception if wrong configuration was using

fix check_tron_job broken due to job misconfigure issue

---

.gitignore
.travis.yml
Makefile
tests/config/config_parse_test.py
tests/config/schedule_parse_test.py
tox.ini
yelp_package/trusty/Dockerfile
yelp_package/xenial/Dockerfile

Run itest_* in docker container because package deps on jenkins hosts.

Yelp's itest changes

---

tron/api/resource.py

we'll need to restart trond for this to take affect :( but its not at all urgent, so nbd

add header required for CORS

---

bin/check_tron_jobs.py
tests/bin/check_tron_jobs_test.py
tron/core/actionrun.py
tron/core/job.py
tron/node.py
tron/serialize/filehandler.py
tron/serialize/runstate/statemanager.py
tron/trondaemon.py

Apparently, check_tron_jobs didn't log anything because of log level. This one should be helpful when next time we got page about check_tron_job failure.

improve monitoring log

---

contrib/namespace_cleanup.sh

This will prompt the question "This will delete the configuration for the %s namespace. Proceed? (y/n):" before it deletes each namespace.

add a script to clean up namespace

---

.pre-commit-config.yaml
docs/conf.py

I can try pointing readthedocs.org at this branch to see if this actually fixes it.

Try to fix doc building

---

tests/api/requestargs_test.py
tests/api/resource_test.py
tron/api/requestargs.py
tron/api/resource.py

encode/decode in requestargs.get_string, use get_string in other get_ funcs

Deal with requestargs encoding in get_string()

---

example-cluster/config/MASTER.yaml
tron/config/config_parse.py
tron/config/schema.py

We have a separate validator for it and it's missing retries attribute.

Fix validation of cleanup action

---

tron/actioncommand.py
tron/serialize/filehandler.py

Confirmed that this fixes the issue we saw on stage

maybe_encode all data in the file serializer

---

tron/utils/state.py

This drops TTFB for large setup from 2.3s to 0.4s

Pre calculate state machine transitions

---

bin/recover_batch.py

we were previously just exiting with code 0 once the batch being recovered
finished. this uses a queue to send the exit code out of the twisted
callback, and the exit_code gotten after the reactor.run() call has finished. we can't
just exit within the callback, since twisted will throw an exception if
we raise sys.exit from inside the callback.

exit the recovery batch with the correct exit code

---

dev/logging.conf
example-cluster/logging.conf
requirements.txt
setup.py
tests/mesos_test.py
tron/logging.conf
tron/mesos.py

This is based off the mesos-runs branch, and also depends on the changes in https://github.com/Yelp/task_processing/pull/104. Putting this up so you can see how it works together.

Get output from Mesos tasks

---

tests/config/config_parse_test.py
tests/core/actionrun_test.py
tests/mcp_test.py
tests/mesos_test.py
tron/config/config_parse.py
tron/config/schema.py
tron/core/actionrun.py
tron/mcp.py
tron/mesos.py

Toggling on will start the framework if it hasn't started already. Toggling off will shut down any existing frameworks and prevent new tasks from starting.

Toggle for Mesos actions

---

tests/config/config_parse_test.py

- extract fixture-like functions
- stop testing yaml parser

Refactor config parse tests

---

bin/check_tron_jobs.py

manually testing. 
I will add unit testing later.

fix duration is longer than 1 day bug

---

.pre-commit-config.yaml
tests/core/job_test.py
tests/mcp_test.py
tox.ini
tron/core/job.py
tron/mcp.py
tron/trondaemon.py

We have recovery now. I don't think we would ever realistically wait for jobs to actually finish.
Also I did some yapf junk, I can undo if you want.

Remove the graceful_shutdown aspect of Tron

---

bin/action_runner.py
tests/bin/action_runner_test.py

It looks fine through running action_runner manually, but I am not sure how to reproduce the error in [TRON-355](https://jira.yelpcorp.com/browse/TRON-355). Any thought?

wait daemon thread finish before exit

---

bin/check_tron_jobs.py
requirements.txt
tests/bin/check_tron_jobs_test.py

I am sure there won't be any bug from _get_seconds_from_duration anymore.

fix _get_seconds_from_duration bug

---

docs/jobs.rst
tests/core/actionrun_test.py
tron/api/adapter.py
tron/commands/display.py
tron/config/config_parse.py
tron/config/schema.py
tron/core/action.py
tron/core/actionrun.py
tronweb/coffee/actionrun.coffee
tronweb/coffee/views.coffee

Delay between actionrun retries

---

bin/tronfig
tests/config/config_parse_test.py
tron/config/config_parse.py
tron/config/config_utils.py

The command is something like:
tronfig tron-playground.yaml -V -n robj-test-service -m ../tron/playground/MASTER.yaml
The output is something like:
Unknown node name batch1-uswest1adevcfff at robj-test-service.NamedConfigFragment.jobs.Job.mesos-test.actions.Action.sleep.node

tronfig checks valid nodes

---

docs/config.rst
docs/developing.rst
docs/man_tronctl.rst
docs/man_trond.rst
docs/man_tronfig.rst
docs/man_tronview.rst
docs/tutorial.rst
tests/bin/check_tron_jobs_test.py
tests/scheduler_test.py
tools/migration/migrate_config_0.2_to_0.3.py
tron/core/recovery.py
tron/event.py
tron/node.py
tron/utils/crontab.py

Spell check all the things

---

.pre-commit-config.yaml
contrib/mock_patch_checker.py
tests/api/adapter_test.py
tests/api/resource_test.py
tests/bin/action_runner_test.py
tests/bin/check_tron_jobs_test.py
tests/commands/client_test.py
tests/config/manager_test.py
tests/core/actionrun_test.py
tests/core/job_test.py
tests/core/recovery_test.py
tests/mesos_test.py
tests/sandbox.py
tests/scheduler_test.py
tests/serialize/runstate/statemanager_test.py

Gotta stave off [the beast](https://engineeringblog.yelp.com/2015/02/assert_called_once-threat-or-menace.html) from going into autospace.

Autospec all the things

---

tests/core/actionrun_test.py
tron/core/actionrun.py

This is useful to recover jobs running on Mesos.

save task id of action run

---

.travis.yml
Makefile
cluster_itests/config/MASTER.yaml
cluster_itests/config/_manifest.yaml
cluster_itests/docker-compose.yml
cluster_itests/mesos.feature
cluster_itests/steps/environment.py
cluster_itests/steps/mesos_steps.py
tox.ini
yelp_package/itest_dockerfiles/mesos/Dockerfile
yelp_package/itest_dockerfiles/mesos/mesos-secrets
yelp_package/itest_dockerfiles/mesos/mesos-slave-secret
yelp_package/itest_dockerfiles/tronmaster/Dockerfile
yelp_package/itest_dockerfiles/zookeeper/Dockerfile

If we are going to have this as a feature, I want confidence that I can make a PR to tron and not break it! :)

Added Tron + Mesos itest framework

---

tests/eventbus_test.py
tests/trondaemon_test.py
tron/config/config_parse.py
tron/config/schema.py
tron/core/action.py
tron/core/actionrun.py
tron/eventbus.py
tron/mcp.py
tron/trondaemon.py

Global: `eventbus_enabled`, per action/actionrun: `triggers_downstream`, `triggered_by`, `on_upstream_rerun`.
All default to `None`.

Add eventbus and cross-job dep related config attributes

---

tron/eventbus.py

dont crash when saving eventbus log into file that already exists

Safer eventbus log saving

---

dev/config/MASTER.yaml
requirements.txt
setup.py
tests/core/actionrun_test.py
tests/core/recovery_test.py
tests/mesos_test.py
tron/core/actionrun.py
tron/core/recovery.py
tron/mesos.py

Goes with https://github.com/Yelp/task_processing/pull/120, works on restart!
Need to test more edge cases and write tests, but wanted to get the overall idea out there for feedback.

Recover unknown mesos actions on startup

---

tests/config/config_parse_test.py
tests/core/action_test.py
tests/eventbus_test.py
tron/config/config_parse.py
tron/eventbus.py

- fix and cover with tests parsing of trigger-related attributes
- convert published string message into event dict
- remove id attribute when storing event
- fix eventbus save to disk procedure

Cross-job deps: fixes in  config  parsing and eventbus

---

tests/config/config_parse_test.py
tests/core/actionrun_test.py
tron/config/config_parse.py
tron/core/actionrun.py
tron/mesos.py

Maybe it's worth in a separated release, so we can roll back easily.

remove percent string support

---

tron/eventbus.py
tron/mcp.py

Fix eventbus reloading even if config option doesn't change.

[fix] Eventbus reload

---

debian/tron.service

im iterating on this, trying to figure out what bits we need from the upstart file

[wip] systemd unit file

---

requirements-dev.txt
tron/core/job_scheduler.py

Testing locally at my dev box.

modify action_id during job migration

---

contrib/migration_script.py

Tested by using `fake_namespace.yaml` and `new_fakens.yaml` in yelsoa-configs/tron/mesosstage
Originally jobs were fake_namespace.hello-world and fake_namespace.hello-world2
Ran:
python migration_script.py ~/yelpsoa-configs/tron/mesosstage/fake_namespace.yaml --old-ns fake_namespace --new-ns new_fakens --server=http://tronplayground-uswest1adevc.dev.yelpcorp.com:8089 --job hello-world2
This succeeded (http://tronplayground-uswest1adevc.dev.yelpcorp.com:8089/web/#home) with the hello-world2 job being moved to the new namespace. The other job (hello-world) was not moved.

Added --job flag to migrate only a single job between namespaces

---

tests/eventbus_test.py
tron/commands/cmd_utils.py
tron/commands/display.py
tron/core/actionrun.py
tron/core/jobrun.py

Jobrun object will be in state running if it has no running Actionruns but some of them are waiting for trigger requirement.

Fix job appearing pending when waiting on trigger requirement

---

.gitignore
Makefile
itest.sh
yelp_package/xenial/Dockerfile

My mom always told me to never use the latest version of everything.

Don't upgrade all the things when building a package

---

yelp_package/trusty/Dockerfile

https://fluffy.yelpcorp.com/i/BKkq3G9sBFvdm2J3hm29593dN9KMddzN.html

Fixed trusty build

---

tests/api/resource_test.py
tron/api/resource.py

I just like kwargs so much.
I feel like if we used kwargs in this situation we would "see" that we were passing a non-dict into a dict? idk.

Allow the tron api get response to handle lists as well as dicts.

---

tron/serialize/runstate/mirror_state_store.py

str doesn't have append function. I'm dumb.

fixed a bug in dynamodb validation function

---

tests/bin/check_tron_jobs_test.py
tron/bin/check_tron_jobs.py

- `get_relevant_action` will never hit the last point where we need to return the last element from the `action_runs` - this only occurred when we would pass "SUCEEDED" as the value for `last_state`
- Removed logic from `get_relevant_run_and_state` which checked whether a job was scheduled and, if not, returned the "NOT_SCHEDULED" state
- Removed tests invoking `get_relevant_run_and_state` since function no longer depends on `PRECIOUS_JOB_ATTR`
- `test_no_job_scheduled_or_queuing` checks that we consider that job in the "SUCEEDED" state
P.S. This is my first official github pull request, I'm so proud 😁

check_tron_jobs no longer alerts if job is not scheduled

---

tronweb/coffee/actionrun.coffee
tronweb/coffee/job.coffee

see the results at http://dev54-uswest1adevc:8089/web/#job/MASTER.testjob0

duration field added to tronweb

---

dev/config/MASTER.yaml

fixed make dev

---

tron/bin/ddbbackup.py

This is for TRON-1130. 
The puppet side is here https://reviewboard.yelpcorp.com/r/407414/
I tested this on mesosstage.  
I didn't add any error checking and assume cron will notify us if that happens. And it's not critical even if it fails.

Set up periodic backup for DynamoDB

---

requirements-docs.txt
requirements.txt

Bump Twisted and Jinja

---

tron/bin/check_tron_jobs.py

This is internal ticket TRON-1166

Put stderr at the front of the check_tron_jobs notification

---

requirements.txt

Bump parso

---

tron/bin/check_tron_jobs.py

This is kinda copy/pasted from the display.py file

Use newlines for the stderr array in check_tron_jobs

---

CHANGELOG.md
README.md
debian/changelog
tron/__init__.py

This is kind of a symbolic thing.
I think we've "made it" with Tron, now that we have gotten to the point where we can make a release and not have to babysit it as it auto-upgrades.
Here's to looking forward to 2.0 with k8s support!?

Released 1.0.0

---

bin/tronctl
bin/tronview

Users don't need to see a stack trace

Provide better user errors when a RequestError happens

---

tests/bin/recover_batch_test.py
tron/bin/recover_batch.py

The diff looks weird here, but I'm just un-nesting this function and reducing the number of lines per function, and not mocking `open()`

Extracted recover_batch yaml loading into a function

---

docs/command_context.rst
tests/command_context_test.py
tron/command_context.py

I'm trying to get a bit warmed up to this codebase in preparation to make it possible to embed graphs into tronview/tronweb for users.

Added new namespace and manual config context variables

---

tron/core/actionrun.py

Due to the way the "returns" are setup here, the return of a delayed action is `None`, which gives a weird message to the user. (cc @smoy )

Always reset the restart delay when manually retrying an action

---

tests/bin/recover_batch_test.py
tron/bin/recover_batch.py

This is the second (and last) bug I found in recovery so far. We mistakenly removed the part of `run` that checks if the status file already has an exit code in https://github.com/Yelp/Tron/pull/700, while trying to DRY it out. If the action_runner completes while Tron is down, the recovery action will hang forever waiting for the status file to be updated again.
I pulled most of the logic into `get_exit_code` to reduce repetition and added test coverage. Based off of https://github.com/Yelp/Tron/pull/707.

Put back check for action runners that have completed in recovery

---

tron/api/controller.py

I've worked with tron forever and I still need these hints

Make UnknownCommandError errors friendlier

---

dev/config/MASTER.yaml
tests/bin/action_runner_test.py
tron/bin/action_runner.py

we export four variables, parsed from the run_id
TRON_JOB_NAMESPACE
TRON_JOB_NAME
TRON_RUN_NUM
TRON_ACTION

tron writes environment variables for the action_runner

---

requirements-minimal.txt
requirements.txt

bump twisted, werkzeug and ecdsa

Address GH alerts

---

itest.sh
yelp_package/trusty/Dockerfile

In theory this will fix our travis build.

fix trusty build

---

tests/mesos_test.py
tron/mesos.py

I... don't really know how this worked before.  Maybe it didn't and I just never tested it.

fixing the clusterman invocation

---

bin/tronctl
docs/man_tronctl.rst

Just being honest until we figure out how to use the latest code on retries.

Be more explicit about rerun/retry behavior in tron till it supports getting new code

---

docs/jobs.rst
tron/bin/check_tron_jobs.py

This is just a first pass at this.
I would like to not change any other behavior in the monitoring script yet, just add the additional option.

Added new page_for_expected_runtime option

---

tests/api/resource_test.py
tron/api/resource.py
tron/mcp.py
tronweb/coffee/models.coffee
tronweb/coffee/navbar.coffee
tronweb/css/tronweb.less
tronweb/index.html

Should always be shown, even when changing tabs.

Add tron version and uptime to frontend navbar

---

tests/serialize/runstate/statemanager_test.py
tron/core/job_scheduler.py
tron/serialize/runstate/statemanager.py

we no longer need it on dynamodb store

Drop consistency check

---

tron/core/actionrun.py
tron/core/jobrun.py

we call it in `job_scheduler.py:135`

Add cancel method on jobrun

---

tron/serialize/runstate/dynamodb_state_store.py

follow up to https://github.com/Yelp/Tron/pull/757, OrderedDict is not thread safe.

Add lock to ordereddict queue in dynamodb store

---

tests/core/job_test.py
tests/serialize/runstate/statemanager_test.py
tests/utils/observer_test.py
tron/core/actionrun.py
tron/core/job.py
tron/core/job_scheduler.py
tron/core/jobrun.py
tron/mcp.py
tron/serialize/runstate/statemanager.py
tron/utils/observer.py

Splitting TRON-1527 up to make it easier to review. 
This PR basically just makes this line work: https://github.com/Yelp/Tron/compare/TRON-1527-job-run-notify?expand=1#diff-d0b76e0212683051bde1771015969b16R271

Tron 1527: state manager gets notified by job runs

---

Makefile
tronweb2/package.json
tronweb2/src/components/ActionGraph/ActionGraph.css
tronweb2/src/components/ActionGraph/ActionGraph.js
tronweb2/src/components/Job/Job.js
tronweb2/src/components/JobsDashboard/JobsDashboard.css
tronweb2/src/components/JobsDashboard/JobsDashboard.js
tronweb2/src/components/NavBar/NavBar.css
tronweb2/src/components/NavBar/NavBar.js
tronweb2/yarn.lock

Added searching by job name, both from the navbar and the homepage. Also made some cosmetic fixes based on what I saw on production clusters - long job names, and trying to make the action graph more legible.

Fix up job pages on tronweb2 and add searching

---

docs/man/tronctl.1
docs/man_tronctl.rst

I forgot to include this in the initial PR :blobsweat:

Add skip-and-publish documentation

---

requirements.txt
tests/kubernetes_test.py
tron/kubernetes.py

This sets up a basic skeleton of Tron's wrapper around a task_processing
task (and is very similar to the corresponding Mesos version: MesosTask)

Add KubernetesTask scaffolding

---

tests/core/actionrun_test.py
tron/core/actionrun.py

This is pretty bare-bones right now and pretty much unusable, but it'll
form the skeleton/base of a k8s ActionRun

Scaffold KubernetesActionRun

---

.pre-commit-config.yaml
tests/kubernetes_test.py
tron/kubernetes.py

This sets up the skeleton for KubernetesCluster (a k8s version of
MesosCluster) and does some of the basic implementation for several
methods when possible/easy

Scaffold out KubernetesCluster (+ some initial implementation)

---

cluster_itests/config/MASTER.yaml
tests/mcp_test.py
tron/kubernetes.py
tron/mcp.py
tron/trondaemon.py

This is generally patterned after the existing MesosClusterRepository.
NOTE: I had to make some configuration-related changes since it seems
like I missed a couple places in the initial config scaffolding commit
and didn't notice until I added code that actually read said config.

Add scaffolding for KubernetesClusterRepository

---

tests/config/config_parse_test.py
tests/kubernetes_test.py
tron/config/config_parse.py
tron/config/schema.py
tron/core/action.py
tron/core/actionrun.py
tron/kubernetes.py

We'll need this for parity with the Mesos implementation and because
it's a good security practice :p

Support adding/dropping capabilities

---

tron/core/actionrun.py

On restarts, we attempt to recreate ActionRuns from state that we
persisted in DynamoDB (or locally) - this generally breaks if we
persisted fields that don't exist in one version and then ran another
version (e.g., when testing new features on our tronplayground instance)

Allow rollbacks from versions with additional information in state_data

---

tron/utils/scribereader.py

It's possible for there to be multiple gigabytes of logs in our logging streams and we don't want Tron sitting there processing these for ages on end. This isn't a silver bullet, but this should help in the meantime

Bail out earlier on large tron logs

---

Makefile

After mergine #896, I forgot to update the makefile to make release for jammy.

update make release

---

Makefile

This fixes make release on jammy devboxes

Fixes make release for jammy

---

dev/config/MASTER.yaml
requirements-minimal.txt
tron/prom_metrics.py

Will add these and create a new release then will pin this latest release everywhere including prod.

Editing some of the messages from previous prs

---

requirements.txt

There's no real changes here other than dropping all the Mesos-related code from task_proc

Use the latest task_proc

---

dev/logging.conf
requirements-minimal.txt
requirements.txt
tests/config/config_parse_test.py
tests/core/action_test.py
tests/core/actionrun_test.py
tests/core/job_test.py
tests/core/recovery_test.py
tests/mcp_test.py
tests/mesos_test.py
tests/serialize/runstate/statemanager_test.py
tron/api/controller.py
tron/config/config_parse.py
tron/config/config_utils.py
tron/config/schema.py
tron/core/action.py
tron/core/actionrun.py
tron/core/job_scheduler.py
tron/core/recovery.py
tron/kubernetes.py
tron/logging.conf
tron/mcp.py
tron/mesos.py
tron/serialize/runstate/__init__.py
tron/serialize/runstate/statemanager.py
tron/trondaemon.py
tron/utils/exitcode.py
yelp_package/itest_dockerfiles/mesos/Dockerfile
yelp_package/itest_dockerfiles/mesos/mesos-secrets
yelp_package/itest_dockerfiles/mesos/mesos-slave-secret

This turned out to be unsafe to to our use of pickles as a serialization format.

Revert the Mesos code deletions

---

tron/utils/scribereader.py

This CLI is being renamed, so let's account for that

Use logreader rathern than vector-reader

---

tronweb3/package.json

init-tronweb3 yarn init

---

tron/serialize/runstate/dynamodb_state_store.py

I'll have a larger testing PR that covers the test changes I mentioned. This standalone fix seems sound for now

Fix loop boundary on getting partitions

---

requirements.txt

Bump task_processing to get the fix from https://github.com/Yelp/task_processing/pull/222

TRON-2333: Bump task_processing for pod truncation fix

---

tests/api/auth_test.py
tron/api/auth.py

It was never going to be a nice implementation, but my first attempt is just so WRONG, I'm ashamed of myself, mpiano--

fix service name extraction logic

---

tronweb/coffee/graph.coffee

We've got some really large charts. Far larger than my test jobs. This lets you see them.
See https://fluffy.yelpcorp.com/i/FZdC5N18gvqKjP6DPNSqZfPH1fpXbknq.png

Halve minZoom for some of our big charts

---

requirements.txt

See https://github.com/kubernetes-client/python?tab=readme-ov-file#compatibility

Bump kubernetes clientlib to the latest supported version

---

Makefile
requirements.txt

I made a silly mistake and didn't increase the attempt counter

Bump task_processing from 1.3.4 to 1.3.5

---

tron/commands/client.py

I got too used to mypy catching this sort of stuff for me...

fix build_url_request when method is None

---

tron/config/config_parse.py
tron/config/schema.py
tron/serialize/runstate/dynamodb_state_store.py
tron/serialize/runstate/statemanager.py

The current limit is probably ok, but is a bit close for comfort. The impact of this should be negligible.

Drop under the limit a bit more for maximum safety
